---
sidebar: sidebar 
permalink: oracle/oracle-dr-overview.html 
keywords: metrocluster, syncmirror, oracle 
summary: Recuperação de desastres de banco de dados Oracle com o ONTAP 
---
= Recuperação de desastres de banco de dados Oracle com o ONTAP
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ../media/


[role="lead"]
Recuperação de desastres refere-se à restauração de serviços de dados após um evento catastrófico, como um incêndio que destrói um sistema de storage ou até mesmo um local inteiro.


NOTE: Esta documentação substitui os relatórios técnicos publicados anteriormente _TR-4591: Oracle Data Protection_ e _TR-4592: Oracle no MetroCluster._

A recuperação de desastres pode ser realizada por replicação simples de dados usando o SnapMirror, é claro, com muitos clientes atualizando réplicas espelhadas quantas vezes por hora.

Para a maioria dos clientes, a recuperação de desastres requer mais do que apenas a posse de uma cópia remota de dados. Isso exige a capacidade de usar esses dados rapidamente. A NetApp oferece duas tecnologias que atendem a essa necessidade: MetroCluster e SnapMirror ative Sync

O MetroCluster se refere ao ONTAP em uma configuração de hardware que inclui armazenamento de baixo nível espelhado e vários recursos adicionais. Soluções integradas, como o MetroCluster, simplificam as infraestruturas de virtualização, aplicações e banco de dados complicadas e com escalabilidade horizontal atuais. Ele substitui vários produtos e estratégias de proteção de dados externos por um storage array simples e central. Ele também fornece backup integrado, recuperação, recuperação de desastres e alta disponibilidade (HA) em um único sistema de storage em cluster.

A sincronização ativa do SnapMirror é baseada no SnapMirror síncrono. Com o MetroCluster, cada controlador ONTAP é responsável por replicar os dados da unidade para um local remoto. Com o SnapMirror active Sync, você tem essencialmente dois sistemas ONTAP diferentes que mantêm cópias independentes dos seus dados LUN, mas cooperam para apresentar uma única instância desse LUN. Do ponto de vista do host, é uma única entidade LUN.

Embora o SnapMirror ative Sync e o MetroCluster funcionem de forma muito diferente internamente, para um host o resultado é muito semelhante. A principal diferença é a granularidade. Se você precisar apenas de cargas de trabalho selecionadas para serem replicadas síncronas, a sincronização ativa do SnapMirror é a melhor opção. Se você precisa replicar ambientes inteiros ou até mesmo data centers, o MetroCluster é uma opção melhor. No momento, a sincronização ativa do SnapMirror é somente SAN, enquanto o MetroCluster é multiprotocolo, incluindo SAN, NFS e SMB.
