---
sidebar: sidebar 
permalink: oracle/oracle-dp-snaprestore.html 
keywords: ontap, snaprestore 
summary: Recuperação rápida de banco de dados Oracle com snapshots 
searchtitle: Recuperação rápida de banco de dados Oracle com snapshots 
---
= SnapRestore
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ../media/


[role="lead"]
A restauração rápida de dados no ONTAP a partir de um snapshot é fornecida pela tecnologia NetApp SnapRestore, que permite restaurar instantaneamente o estado de um volume AFF ou de um ASA LUN.

Quando um conjunto de dados essencial não está disponível, as operações de negócios essenciais estão inativas. As fitas podem quebrar, e até mesmo as restaurações de backups baseados em disco podem ser lentas para serem transferidas pela rede. O SnapRestore evita esses problemas fornecendo restauração quase instantânea de conjuntos de dados. Mesmo os bancos de dados em escala de petabyte podem ser completamente restaurados com apenas alguns minutos de esforço.

Embora a tecnologia básica seja a mesma nas plataformas AFF e ASA, elas são usadas de maneiras ligeiramente diferentes.



[[aff-overview]]
== Visão geral da AFF

Existem duas formas de SnapRestore em um sistema AFF: baseado em arquivos e baseado em volumes:

* Arquivos AFF individuais, LUNs e namespaces AFF, assim como LUNs e namespaces ASA individuais, podem ser restaurados em segundos, seja um LUN de 2TB ou um arquivo de 4KB.
* Todo o conteúdo de um volume AFF pode ser restaurado em segundos, seja ele de 10GB ou 100TB de dados.


O motivo pelo qual SnapRestore funciona de forma tão rápida e eficiente reside na natureza de um snapshot, que é essencialmente uma visão paralela somente leitura do conteúdo de um volume, LUN ou namespace em um ponto específico no tempo. Os blocos ativos são os blocos reais que podem ser alterados, enquanto o snapshot é uma visão somente leitura do estado dos blocos que constituem os arquivos e LUNs no momento em que o snapshot foi criado.

ONTAP permite apenas acesso de leitura aos dados do snapshot, mas os dados podem ser reativados com SnapRestore. O snapshot é reativado como uma visualização de leitura e gravação dos dados, retornando os dados ao seu estado anterior. SnapRestore pode operar no nível de volume, arquivo, LUN ou namespace. A tecnologia é essencialmente a mesma, com algumas pequenas diferenças de comportamento.



[[aff-volume-snaprestore]]
=== AFF Volume SnapRestore

A restauração baseada em volume SnapRestore retorna o conteúdo de um volume inteiro a um estado anterior. Essa operação não requer movimentação de dados, o que significa que o processo de restauração é essencialmente instantâneo, embora a operação via API ou CLI possa levar alguns segundos para ser processada. Restaurar 1GB de dados não é mais complicado ou demorado do que restaurar 1PB de dados. Essa capacidade é o principal motivo pelo qual muitos clientes corporativos migram para sistemas de armazenamento ONTAP. Ela oferece um RTO medido em segundos, mesmo para os maiores conjuntos de dados.

Uma desvantagem para o SnapRestore baseado em volume é causada pelo fato de que as alterações dentro de um volume são cumulativas ao longo do tempo. Portanto, cada snapshot e os dados de arquivo ativos dependem das alterações que levam a esse ponto. Reverter um volume para um estado anterior significa descartar todas as alterações subsequentes que foram feitas aos dados. O que é menos óbvio, no entanto, é que isso inclui instantâneos criados posteriormente. Isso nem sempre é desejável.

Por exemplo, um SLA de retenção de dados pode especificar 30 dias de backups noturnos. Restaurar um conjunto de dados para um instantâneo criado há cinco dias com o volume SnapRestore descartaria todos os snapshots criados nos cinco dias anteriores, violando o SLA.

Existem várias opções disponíveis para resolver esta limitação:

. Os dados podem ser copiados de um snapshot anterior, em vez de executar um SnapRestore de todo o volume. Esse método funciona melhor com conjuntos de dados menores.
. Um snapshot pode ser clonado em vez de restaurado. A limitação a essa abordagem é que o snapshot de origem é uma dependência do clone. Portanto, ele não pode ser excluído a menos que o clone também seja excluído ou seja dividido em um volume independente.
. Uso de SnapRestore baseado em arquivos.




[[aff-file-snaprestore]]
=== AFF Arquivo SnapRestore

A restauração baseada em arquivos SnapRestore é um processo mais granular baseado em snapshot, usado com volumes AFF. Em vez de reverter o estado de um volume inteiro, o estado de um arquivo, LUN ou namespace individual é revertido. Não é necessário excluir snapshots, nem essa operação cria qualquer dependência de um snapshot anterior. O arquivo ou LUN fica imediatamente disponível no volume ativo.

Nenhuma movimentação de dados é necessária durante a restauração SnapRestore de um arquivo ou LUN. No entanto, algumas atualizações internas de metadados são necessárias para refletir o fato de que os blocos subjacentes nos dados restaurados agora existem tanto em um snapshot quanto no volume ativo. Não deve haver impacto no desempenho, mas esse processo bloqueia a criação de snapshots até que seja concluído. A taxa de processamento é de aproximadamente 5GBps (18TB/hora), com base no tamanho total dos arquivos restaurados.



[[asa-lunnamespace-restoration]]
== Restauração de LUN/namespace ASA

A restauração de dados no ASA é semelhante à AFF SnapRestore. Os dados são simplesmente restaurados para um estado anterior. O processo é quase instantâneo e não requer movimentação de dados. Ele também possui as mesmas limitações, incluindo a exigência de que a restauração de um snapshot resulte na exclusão de snapshots excluídos posteriormente. Se isso for problemático, existem duas opções. Primeiro, um LUN/namespace pode ser clonado a partir de um snapshot anterior, mantendo o volume de origem inalterado. Este é um processo instantâneo e eficiente em termos de espaço. Ele essencialmente cria uma cópia de leitura e gravação do ponteiro somente leitura para os blocos em um snapshot. Uma segunda opção é via API REST, que pode usar a mesma lógica de arquivo único SnapRestore usada em sistemas AFF. O resultado é uma restauração instantânea de um LUN/namespace usando os dados de um snapshot e todos os snapshots são preservados.
