---
sidebar: sidebar 
permalink: oracle/oracle-dp-consistency-group-backup.html 
keywords: oracle, data, protection, consistency, group, backup, volume, archive, log, redo, controlfiles 
summary: Backups de grupos de consistência para bancos de dados Oracle no ONTAP 
searchtitle: Backups de grupos de consistência de banco de dados Oracle 
---
= Backups de grupos de consistência
:allow-uri-read: 


[role="lead"]
Para o backup mais simples possível, basta colocar todo o banco de dados Oracle em um único volume ONTAP, LUN ou namespace NVMe.

Proteger os arquivos de dados, logs de arquivamento, redo logs e arquivos de controle com um único Snapshot é um método válido de backup, restauração e replicação. No entanto, o RPO é limitado ao ponto do próprio backup. É adequado para um RPO de uma hora ou mais. Se um banco de dados abranger volumes AFF ou unidades de storage ASA, grupos de consistência serão necessários usando uma das ferramentas discutidas anteriormente.

Por exemplo, todo o banco de dados pode estar em um único volume AFF com a seguinte programação de snapshots:

* 72 instantâneos por hora
* 30 instantâneos todas as noites
* 12 instantâneos mensais


Isso proporciona um RPO de uma hora no período contínuo das 72 horas anteriores, além de backups noturnos e mensais adicionais. Vários bancos de dados ou arquivos de aplicativos também podem ser incluídos em um único volume ou conjunto de snapshots de grupo de consistência para fornecer backups consistentes em um ambiente maior.
