= Agregados SSD AFF e Zonas de Disponibilidade de Armazenamento ASA
:allow-uri-read: 


Espaço livre é definido como qualquer espaço não utilizado para dados reais e inclui espaço não alocado no próprio agregado e espaço não utilizado dentro dos volumes constituintes. Thin provisioning também deve ser considerado. Por exemplo, um AFF volume pode conter um LUN de 1TB, do qual apenas 50% é utilizado por dados reais. Em um ambiente com thin provisioning, isso apareceria corretamente como consumindo 500GB de espaço. No entanto, em um ambiente com provisionamento completo, a capacidade total de 1TB aparece em uso. Os 500GB de espaço não alocado ficam ocultos. Esse espaço não é utilizado por dados reais e, portanto, deve ser incluído no cálculo do espaço livre total.

As recomendações da NetApp para sistemas de storage usados para aplicações empresariais são as seguintes:



== Agregados SSD AFF e Zonas de Disponibilidade de Armazenamento ASA


TIP: *A NetApp recomenda* um mínimo de 10% de espaço livre. Isso inclui todo o espaço não utilizado, incluindo espaço livre dentro do agregado ou de um volume e qualquer espaço livre alocado devido ao uso de provisionamento completo, mas não é usado por dados reais. O espaço lógico não é importante, a questão é quanto espaço físico livre real está disponível para armazenamento de dados.

A recomendação de 10% de espaço livre é muito conservadora. Agregados SSD podem dar suporte a workloads em níveis ainda mais altos de utilização sem afetar a performance. No entanto, à medida que a utilização do agregado aumenta, o risco de ficar sem espaço também aumenta se a utilização não for monitorada com cuidado. Além disso, ao executar um sistema com 99% de capacidade pode não incorrer em uma penalidade de desempenho, mas provavelmente incorreria em esforço de gerenciamento tentando impedi-lo de preencher completamente enquanto hardware adicional é solicitado, e pode levar algum tempo para adquirir e instalar unidades adicionais.



== Agregados de HDD, incluindo agregados Flash Pool


TIP: *A NetApp recomenda* um mínimo de 15% de espaço livre quando as unidades giratórias são usadas. Isso inclui todo o espaço não utilizado, incluindo espaço livre dentro do agregado ou de um volume e qualquer espaço livre alocado devido ao uso de provisionamento completo, mas não é usado por dados reais. O desempenho será impactado à medida que o espaço livre se aproxima de 10%.
