= Fibre Channel
:allow-uri-read: 




[[fiber-channel]]
=== Fibre Channel

A partir do ONTAP 9.19.1, a conexão direta FC é suportada tanto com FC-SAN (SCSI) tradicional quanto com NVMe/FC, com adaptadores FC de sistema de storage selecionados. Os HBAs estabelecerão uma conexão FC ponto a ponto padrão. Antes do ONTAP 9.19.1, os sistemas de storage ONTAP exigem NPIV, o que significa que o sistema de storage deve estar conectado a um switch FC que também suporte NPIV.



[[iscsi-and-nvmetcp]]
=== ISCSI e NVMe/TCP

Um host usando iSCSI ou NVMe/TCP pode ser conetado diretamente a um sistema de storage e operar normalmente. A razão é pathing. Conexões diretas a dois controladores de storage diferentes resultam em dois caminhos independentes para o fluxo de dados. A perda de caminho, porta ou controlador não impede que o outro caminho seja usado.



[[nfs]]
=== NFS

O armazenamento NFS com conexão direta pode ser usado, mas com uma limitação significativa - o failover não funcionará sem um esforço significativo de script, o que seria da responsabilidade do cliente.

O motivo pelo qual o failover sem interrupções é complicado com o storage NFS com conexão direta é o roteamento que ocorre no sistema operacional local. Por exemplo, suponha que um host tenha um endereço IP de 192.168.1.1/24 e esteja conetado diretamente a um controlador ONTAP com um endereço IP de 192.168.1.50/24. Durante o failover, esse endereço 192.168.1.50 pode fazer failover para a outra controladora e estará disponível para o host, mas como o host deteta sua presença? O endereço 192.168.1.1 original ainda existe na NIC host que não se coneta mais a um sistema operacional. O tráfego destinado a 192.168.1.50 continuaria a ser enviado para uma porta de rede inoperável.

A segunda placa de rede do sistema operacional poderia ser configurada como 192.168.1.2 e seria capaz de se comunicar com o endereço 192.168.1.50 após a falha, mas as tabelas de roteamento locais teriam, por padrão, um e somente um endereço para comunicação com a sub-rede 192.168.1.0/24. Um administrador de sistemas poderia criar uma estrutura de script que detectaria uma falha na conexão de rede e alteraria as tabelas de roteamento locais ou ativaria e desativaria interfaces. O procedimento exato dependeria do sistema operacional em uso.

Na prática, os clientes da NetApp têm NFS com conexão direta, mas normalmente apenas para workloads em que as pausas de e/S durante failovers são aceitáveis. Quando os suportes rígidos são usados, não deve haver nenhum erro de e/S durante essas pausas. O IO deve travar até que os serviços sejam restaurados, seja por um failback ou intervenção manual para mover endereços IP entre NICs no host.
