---
sidebar: sidebar 
permalink: mssql/mssql-data-protection-ASA.html 
keywords: MSSQL,SQL Server, SnapCenter, data protection, app-consistent backup, ONTAP 
summary: Proteção de bancos de dados Microsoft SQL Server no ONTAP com comandos SnapCenter e T-SQL. 
searchtitle: Proteção de dados do Microsoft SQL Server com o software de gerenciamento NetApp 
---
= Proteção de dados
:allow-uri-read: 
:imagesdir: ../media/


[role="lead"]
As estratégias de backup de banco de dados devem ser baseadas em requisitos de negócios identificados, não em recursos teóricos. Ao combinar a tecnologia Snapshot da ONTAP e aproveitar as API do Microsoft SQL Server, você pode rapidamente fazer backup consistente de aplicativos, independentemente do tamanho dos bancos de dados do usuário. Para requisitos de gerenciamento de dados mais avançados ou com escalabilidade horizontal, a NetApp oferece SnapCenter.



== SnapCenter

O SnapCenter é o software de proteção de dados da NetApp para aplicações empresariais. Os bancos de dados do SQL Server podem ser protegidos rápida e facilmente com o plug-in do SnapCenter para SQL Server e com operações do SO gerenciadas pelo plug-in do SnapCenter para Microsoft Windows.

A instância do SQL Server pode ser uma configuração autônoma, uma instância de cluster de failover ou pode estar sempre no grupo de disponibilidade. O resultado é que, a partir de um painel único, os bancos de dados podem ser protegidos, clonados e restaurados da cópia primária ou secundária. O SnapCenter pode gerenciar bancos de dados do SQL Server tanto no local, na nuvem e configurações híbridas. Cópias de banco de dados também podem ser criadas em poucos minutos no host original ou alternativo para desenvolvimento ou para fins de geração de relatórios.

O SQL Server também requer coordenação entre o sistema operacional e o armazenamento para garantir que os dados corretos estejam presentes em snapshots no momento da criação. Na maioria dos casos, o único método seguro para fazer isso é com SnapCenter ou T-SQL. Os instantâneos criados sem essa coordenação adicional podem não ser recuperáveis de forma confiável.

Para obter mais detalhes sobre o plug-in do SQL Server para SnapCenter, link:https://www.netapp.com/pdf.html?item=/media/12400-tr4714.pdf["TR-4714: Guia de práticas recomendadas para SQL Server usando NetApp SnapCenter"^]consulte .



== Proteção de banco de dados usando snapshots T-SQL

No SQL Server 2022, a Microsoft introduziu snapshots T-SQL que oferece um caminho para a execução de scripts e automação de operações de backups. Em vez de executar cópias de tamanho completo, você pode preparar o banco de dados para snapshots. Depois que o banco de dados estiver pronto para backup, você poderá aproveitar as APIs REST do ONTAP para criar snapshots.

O seguinte é um exemplo de fluxo de trabalho de backup:

. Congelar um banco de dados com comando ALTER. Ele prepara o banco de dados para um snapshot consistente no storage subjacente. Após o congelamento, você pode descongelar o banco de dados e gravar o instantâneo com o comando BACKUP.
. Execute snapshots de vários bancos de dados nas unidades de armazenamento simultaneamente com os novos comandos DO GRUPO DE backup e DO SERVIDOR DE BACKUP.
. Se a carga de trabalho do banco de dados for expandida em várias unidades de armazenamento, crie grupos de consistência para simplificar a tarefa de gerenciamento. O grupo de consistência é um conjunto de unidades de armazenamento que são gerenciadas como uma única unidade.
. Execute backups COMPLETOS ou backups COMPLETOS Copy_ONLY. Esses backups também são gravados em msdb.
. Execute recuperação pontual usando backups de log feitos com a abordagem de streaming normal após o backup COMPLETO do snapshot. Backups diferenciais de streaming também são suportados, se desejado.


Para saber mais, link:https://learn.microsoft.com/en-us/sql/relational-databases/databases/create-a-database-snapshot-transact-sql?view=sql-server-ver16["Documentação da Microsoft para saber sobre os snapshots T-SQL"^]consulte .


TIP: *A NetApp recomenda* usar o SnapCenter para criar cópias Snapshot. O método T-SQL descrito acima também funciona, mas o SnapCenter oferece automação completa no processo de backup, restauração e clonagem. Ele também executa a descoberta para garantir que os snapshots corretos estejam sendo criados.
