---
sidebar: sidebar 
permalink: mssql/mssql-shared-vs-dedicated.html 
keywords: MSSQL,SQL Server, multiple instances, dedicated instance, ONTAP 
summary: Implantação de instância do Microsoft SQL Server 
searchtitle: Implantação de instância do Microsoft SQL Server 
---
= Instância compartilhada versus instância dedicada
:hardbreaks:
:allow-uri-read: 
:icons: font
:linkattrs: 
:imagesdir: ../media/


[role="lead"]
O SQL Server pode ser configurado como uma única instância por servidor ou como várias instâncias. A decisão certa geralmente depende de fatores como se o servidor deve ser usado para produção ou desenvolvimento, se a instância é considerada crítica para as operações de negócios e metas de desempenho.

Configurações de instâncias compartilhadas podem ser inicialmente mais fáceis de configurar, mas podem levar a problemas nos quais os recursos ficam divididos ou bloqueados, o que, por sua vez, causa problemas de desempenho para outros aplicativos que têm bancos de dados hospedados na instância compartilhada do SQL Server.

A solução de problemas de desempenho pode ser complicada porque você precisa descobrir qual instância é a causa principal. Esta questão é ponderada em relação aos custos das licenças do sistema operacional e das licenças do SQL Server. Se o desempenho do aplicativo for primordial, uma instância dedicada é altamente recomendada.

A Microsoft licencia o SQL Server por núcleo no nível do servidor e não por instância. Por esse motivo, os administradores de banco de dados são tentados a instalar quantas instâncias do SQL Server o servidor pode lidar para economizar nos custos de licenciamento, o que pode levar a grandes problemas de desempenho posteriormente.


TIP: *A NetApp recomenda* escolher instâncias dedicadas do SQL Server sempre que possível para obter o desempenho ideal.
