---
sidebar: sidebar 
permalink: vmware/vmware-vsphere-overview.html 
keywords: introduction, unified storage, virtual volumes, storage efficiency, hybrid cloud 
summary: O ONTAP é uma solução de storage líder para ambientes VMware vSphere há quase duas décadas e continua adicionando recursos inovadores para simplificar o gerenciamento e reduzir custos. Este documento apresenta a solução ONTAP para vSphere, incluindo as informações mais recentes sobre produtos e as melhores práticas, para simplificar a implantação, reduzir riscos e simplificar o gerenciamento. 
---
= VMware vSphere com ONTAP
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ../media/


[role="lead"]
A ONTAP serviu como uma solução de armazenamento de dados de primeira linha para o VMware vSphere e, mais recentemente, para ambientes Cloud Foundation desde sua introdução no data center moderno em 2002. Ele continua a introduzir recursos inovadores que simplificam o gerenciamento e reduzem custos.

Este documento apresenta a solução ONTAP para vSphere, destacando as informações mais recentes do produto e as práticas recomendadas para simplificar a implantação, mitigar riscos e simplificar o gerenciamento.


NOTE: Esta documentação substitui os relatórios técnicos publicados anteriormente _TR-4597: VMware vSphere for ONTAP_

As práticas recomendadas complementam outros documentos, como guias e listas de compatibilidade. Eles são desenvolvidos com base em testes de laboratório e extensa experiência de campo por engenheiros e clientes da NetApp. Elas podem não ser as únicas práticas suportadas que funcionam em todos os ambientes, mas são geralmente as soluções mais simples que atendem às necessidades da maioria dos clientes.

Este documento se concentra em recursos nas versões recentes do ONTAP (9.x) executadas no vSphere 7,0 ou posterior. Consulte https://imt.netapp.com/matrix/#search["Ferramenta de Matriz de interoperabilidade (IMT)"^] e https://www.vmware.com/resources/compatibility/search.php?deviceCategory=san["Guia de compatibilidade da VMware"^] para obter detalhes relacionados a lançamentos específicos.
