---
sidebar: sidebar 
permalink: vmware/vmware-vsphere-overview.html 
keywords: introduction, unified storage, virtual volumes, storage efficiency, hybrid cloud 
summary: O ONTAP é uma solução de storage líder para ambientes VMware vSphere há quase duas décadas e continua adicionando recursos inovadores para simplificar o gerenciamento e reduzir custos. Este documento apresenta a solução ONTAP para vSphere, incluindo as informações mais recentes sobre produtos e as melhores práticas, para simplificar a implantação, reduzir riscos e simplificar o gerenciamento. 
---
= VMware vSphere com ONTAP
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ../media/


[role="lead"]
O ONTAP é uma solução de storage líder para ambientes VMware vSphere há quase duas décadas e continua adicionando recursos inovadores para simplificar o gerenciamento e reduzir custos. Este documento apresenta a solução ONTAP para vSphere, incluindo as informações mais recentes sobre produtos e as melhores práticas, para simplificar a implantação, reduzir riscos e simplificar o gerenciamento.


NOTE: Esta documentação substitui os relatórios técnicos publicados anteriormente _TR-4597: VMware vSphere for ONTAP_

As práticas recomendadas complementam outros documentos, como guias e listas de compatibilidade. Eles são desenvolvidos com base em testes de laboratório e extensa experiência de campo por engenheiros e clientes da NetApp. Elas podem não ser as únicas práticas suportadas que funcionam em todos os ambientes, mas são geralmente as soluções mais simples que atendem às necessidades da maioria dos clientes.

Este documento se concentra em recursos nas versões recentes do ONTAP (9.x) executadas no vSphere 7,0 ou posterior. Consulte https://imt.netapp.com/matrix/#search["Ferramenta de Matriz de interoperabilidade do NetApp"^] e https://www.vmware.com/resources/compatibility/search.php?deviceCategory=san["Guia de compatibilidade da VMware"^] para obter detalhes relacionados a lançamentos específicos.



== Por que o ONTAP para vSphere?

Há muitos motivos pelos quais dezenas de milhares de clientes escolheram o ONTAP como sua solução de storage para o vSphere, como um sistema de storage unificado compatível com protocolos SAN e nas, recursos robustos de proteção de dados usando snapshots com uso eficiente de espaço e diversas ferramentas para ajudar você a gerenciar dados de aplicações. O uso de um sistema de storage separado do hipervisor permite descarregar várias funções e maximizar seu investimento nos sistemas de host vSphere. Essa abordagem não só garante que os recursos de host estejam focados nas cargas de trabalho dos aplicativos, mas também evita efeitos aleatórios de desempenho nos aplicativos das operações de storage.

O uso do ONTAP em conjunto com o vSphere é uma ótima combinação que permite reduzir as despesas de hardware do host e software VMware. Você também pode proteger seus dados a um custo menor com alta performance consistente. Como as cargas de trabalho virtualizadas são móveis, você pode explorar diferentes abordagens usando o Storage vMotion para mover VMs entre armazenamentos de dados VMFS, NFS ou vVols, tudo no mesmo sistema de storage.

Aqui estão os principais fatores que os clientes valorizam hoje:

* *Armazenamento unificado.* Os sistemas que executam o ONTAP são unificados de várias maneiras significativas. Originalmente, essa abordagem se referia aos protocolos nas e SAN, e a ONTAP continua a ser uma plataforma líder para SAN, juntamente com sua força original no nas. No mundo vSphere, essa abordagem também pode significar um sistema unificado para infraestrutura de desktop virtual (VDI), juntamente com a infraestrutura de servidor virtual (VSI). Os sistemas que executam o ONTAP geralmente são mais baratos para VSI do que os arrays empresariais tradicionais e ainda têm recursos avançados de eficiência de storage para lidar com a VDI no mesmo sistema. O ONTAP também unifica uma variedade de Mídia de armazenamento, de SSDs a SATA, e pode estender isso facilmente para a nuvem. Não é necessário comprar um array flash para obter desempenho, um array SATA para arquivos e sistemas separados para a nuvem. ONTAP une todos eles.
* *Gerenciamento baseado em políticas de armazenamento e volumes virtuais.* O NetApp foi um dos primeiros parceiros de design da VMware no desenvolvimento do vSphere Virtual volumes (vVols), fornecendo informações arquitetônicas e suporte antecipado para vVols e VMware vSphere APIs for Storage Awareness (VASA). Essa abordagem não só trouxe gerenciamento granular de storage de VM para o VMFS, mas também suportou a automação do provisionamento de storage por meio do gerenciamento baseado em políticas de storage. Com essa abordagem, os arquitetos de storage podem projetar pools de storage com recursos diferentes que podem ser facilmente consumidos pelos administradores de VM. A ONTAP lidera o setor de storage na escala da evolução, dando suporte a centenas de milhares de vols em um único cluster, enquanto os fornecedores de array empresarial e flash arrays menores oferecem suporte a apenas milhares de vols por array. O NetApp também está impulsionando a evolução do gerenciamento granular de VM com futuros recursos para suporte ao vVols 3,0.
* *Eficiência de armazenamento.* Embora a NetApp tenha sido a primeira a fornecer deduplicação para cargas de trabalho de produção, essa inovação não foi a primeira ou última nessa área. Ele começou com snapshots, um mecanismo de proteção de dados com uso eficiente de espaço sem efeito de performance e a tecnologia FlexClone para fazer cópias de leitura/gravação instantaneamente das VMs para uso em produção e backup. A NetApp passou a fornecer recursos inline, incluindo deduplicação, compactação e deduplicação de bloco zero, para aproveitar a maior parte do storage com SSDs caros. Mais recentemente, o ONTAP adicionou a capacidade de embalar operações e/S menores em um bloco de disco usando a compactação. A combinação desses recursos resultou em que os clientes viram economias de até 5:1 dólares para VSI e até 30:1 dólares para VDI.
* *Nuvem híbrida.* Sejam usadas para nuvem privada no local, infraestrutura de nuvem pública ou uma nuvem híbrida que combina o melhor dos dois, as soluções da ONTAP ajudam você a criar seu Data Fabric para otimizar e otimizar o gerenciamento de dados. Comece com sistemas all-flash de alta performance e combine-os com sistemas de storage em disco ou em nuvem para proteção de dados e computação em nuvem. Aproveite o suporte avançado para as tecnologias OpenStack e de contêiner, conforme necessário. O NetApp também oferece backup baseado em nuvem (nuvem SnapMirror, Cloud Backup Service e Cloud Sync) e ferramentas de arquivamento e disposição em camadas de storage (FabricPool) para ONTAP para ajudar a reduzir as despesas operacionais e aproveitar o amplo alcance da nuvem.
* *E muito mais.* Aproveite a performance extrema dos arrays NetApp AFF A-Series para acelerar sua infraestrutura virtualizada e gerenciar custos. Aproveite operações totalmente ininterruptas, desde a manutenção até os upgrades até a substituição completa do seu sistema de storage, usando clusters ONTAP com escalabilidade horizontal. Proteger dados em repouso com os recursos de criptografia do NetApp sem custo adicional. Certifique-se de que o desempenho atenda aos níveis de serviço de negócios por meio de recursos de qualidade de serviço refinados. Todos eles fazem parte da ampla variedade de recursos fornecidos com o ONTAP, o software de gerenciamento de dados empresariais líder do setor.

