---
sidebar: sidebar 
permalink: vmware/vmware-vsphere-network.html 
keywords: vSphere, datastore, VMFS, FC, FCoE, NVMe-FC, iSCSI, NFS, vVols 
summary: Esta página descreve as práticas recomendadas para a implementação de uma solução de storage ONTAP em um ambiente VMware vSphere. 
---
= Configuração de rede
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ../media/


[role="lead"]
A configuração das configurações de rede ao usar o vSphere com sistemas executando o ONTAP é simples e semelhante a outras configurações de rede.

Aqui estão algumas coisas a considerar:

* Separe o tráfego de rede de armazenamento de outras redes. Uma rede separada pode ser obtida usando uma VLAN dedicada ou switches separados para armazenamento. Se a rede de armazenamento partilhar caminhos físicos, como uplinks, poderá necessitar de portas de QoS ou uplink adicionais para garantir uma largura de banda suficiente. Não conete os hosts diretamente ao storage a menos que o guia de solução o chame especificamente; use switches para ter caminhos redundantes e permitir que o VMware HA funcione sem intervenção.
* Jumbo Frames devem ser usados se suportado pela sua rede. Se forem usados, certifique-se de que estejam configurados de forma idêntica em todos os dispositivos de rede, VLANs e assim por diante no caminho entre o armazenamento e o host ESXi. Caso contrário, você pode ver problemas de desempenho ou conexão. A MTU também deve ser definida de forma idêntica no switch virtual ESXi, na porta VMkernel e também nas portas físicas ou grupos de interface de cada nó ONTAP.
* O NetApp recomenda apenas desativar o controle de fluxo de rede nas portas de interconexão de cluster dentro de um cluster ONTAP. A NetApp não faz outras recomendações sobre práticas recomendadas em relação ao controle de fluxo para as portas de rede restantes usadas para tráfego de dados. Você deve ativá-lo ou desativá-lo conforme necessário.  https://www.netapp.com/pdf.html?item=/media/16885-tr-4182pdf.pdf["TR-4182"^]Consulte para obter mais informações sobre o controlo de fluxo.
* Quando os storages ESXi e ONTAP estão conetados a redes de armazenamento Ethernet, a NetApp recomenda configurar as portas Ethernet às quais esses sistemas se conetam como portas de borda de protocolo de árvore de expansão rápida (RSTP) ou usando o recurso Cisco PortFast. A NetApp recomenda ativar o recurso de tronco de porta de árvore de expansão rápida em ambientes que usam o recurso Cisco PortFast e que têm entroncamento de VLAN 802,1Q habilitado para o servidor ESXi ou para os storages ONTAP.
* A NetApp recomenda as seguintes práticas recomendadas para agregação de links:
+
** Use switches que suportam agregação de links de portas em dois chassis de switch separados usando uma abordagem de grupo de agregação de links de vários gabinetes, como o Virtual PortChannel (VPC) da Cisco.
** Desative o LACP para portas de switch conetadas ao ESXi a menos que você esteja usando dvSwitches 5,1 ou posterior com o LACP configurado.
** Use o LACP para criar agregados de link para sistemas de storage ONTAP com grupos de interface multimodo dinâmico com hash IP.
** Use uma política de agrupamento de hash IP no ESXi.




A tabela a seguir fornece um resumo dos itens de configuração de rede e indica onde as configurações são aplicadas.

|===
| Item | ESXi | Interrutor | Nó | SVM 


| Endereço IP | VMkernel | Não** | Não** | Sim 


| Agregação de links | Switch virtual | Sim | Sim | Não* 


| VLAN | Grupos de portas VMkernel e VM | Sim | Sim | Não* 


| Controle de fluxo | NIC | Sim | Sim | Não* 


| Spanning tree | Não | Sim | Não | Não 


| MTU (para quadros jumbo) | Switch virtual e porta VMkernel (9000) | Sim (definido para máx.) | Sim (9000) | Não* 


| Grupos de failover | Não | Não | Sim (criar) | Sim (selecione) 
|===
*Os LIFs SVM se conetam a portas, grupos de interfaces ou interfaces VLAN que têm VLAN, MTU e outras configurações. No entanto, as configurações não são gerenciadas no nível da SVM.

**Esses dispositivos têm endereços IP próprios para gerenciamento, mas esses endereços não são usados no contexto da rede de armazenamento ESXi.



== SAN (FC, NVMe/FC, iSCSI, NVMe/TCP), RDM

O ONTAP oferece storage de bloco de classe empresarial para VMware vSphere usando iSCSI tradicional e Fibre Channel Protocol (FCP), bem como o protocolo de bloco de última geração, altamente eficiente e de alta performance, o NVMe over Fabrics (NVMe-of), com suporte a NVMe/FC e NVMe/TCP.

Para obter as práticas recomendadas detalhadas para a implementação de protocolos de bloco para armazenamento de VM com o vSphere e o ONTAP, consulte link:vmware-vsphere-datastores-san.html["Datastores e Protocolos - SAN"]



== NFS

O vSphere permite que os clientes usem arrays NFS de classe empresarial para fornecer acesso simultâneo a datastores para todos os nós em um cluster ESXi. Como mencionado na link:vmware-vsphere-datastores-top.html["armazenamentos de dados"] seção, há alguns benefícios de visibilidade de eficiência de storage e facilidade de uso ao usar o NFS com vSphere.

Para obter as melhores práticas recomendadas, consulte link:vmware-vsphere-datastores-nfs.html["Datastores e Protocolos - NFS"]



== Ligação direta em rede

Administradores de virtualização às vezes preferem simplificar suas infraestruturas removendo switches de rede da configuração. Isso permite a criação de uma solução mais autossuficiente, com menos componentes e menos espaço necessário no rack. Existem algumas restrições importantes que dependem do protocolo em uso.



=== Fibre Channel

A partir do ONTAP 9.19.1, a conexão direta FC é suportada tanto com FC-SAN (SCSI) tradicional quanto com NVMe/FC, com adaptadores FC de sistema de storage selecionados. Os HBAs estabelecerão uma conexão FC ponto a ponto padrão.

Antes do ONTAP 9.19.1, os sistemas de storage ONTAP exigem NPIV, o que significa que o sistema de storage deve estar conectado a um switch FC que também suporte NPIV.



=== ISCSI e NVMe/TCP

Um host usando iSCSI ou NVMe/TCP pode ser conetado diretamente a um sistema de storage e operar normalmente. A razão é pathing. Conexões diretas a dois controladores de storage diferentes resultam em dois caminhos independentes para o fluxo de dados. A perda de caminho, porta ou controlador não impede que o outro caminho seja usado.



=== NFS

O armazenamento NFS com conexão direta pode ser usado, mas com uma limitação significativa - o failover não funcionará sem um esforço significativo de script, o que seria da responsabilidade do cliente.

O motivo pelo qual o failover sem interrupções é complicado com o storage NFS com conexão direta é o roteamento que ocorre no sistema operacional local. Por exemplo, suponha que um host tenha um endereço IP de 192.168.1.1/24 e esteja conetado diretamente a um controlador ONTAP com um endereço IP de 192.168.1.50/24. Durante o failover, esse endereço 192.168.1.50 pode fazer failover para a outra controladora e estará disponível para o host, mas como o host deteta sua presença? O endereço 192.168.1.1 original ainda existe na NIC host que não se coneta mais a um sistema operacional. O tráfego destinado a 192.168.1.50 continuaria a ser enviado para uma porta de rede inoperável.

A segunda placa de rede do sistema operacional poderia ser configurada como 192.168.1.2 e seria capaz de se comunicar com o endereço 192.168.1.50 após a falha, mas as tabelas de roteamento locais teriam, por padrão, um e somente um endereço para comunicação com a sub-rede 192.168.1.0/24. Um administrador de sistemas poderia criar uma estrutura de script que detectaria uma falha na conexão de rede e alteraria as tabelas de roteamento locais ou ativaria e desativaria interfaces. O procedimento exato dependeria do sistema operacional em uso.

Na prática, os clientes da NetApp têm NFS com conexão direta, mas normalmente apenas para workloads em que as pausas de e/S durante failovers são aceitáveis. Quando os suportes rígidos são usados, não deve haver nenhum erro de e/S durante essas pausas. O IO deve travar até que os serviços sejam restaurados, seja por um failback ou intervenção manual para mover endereços IP entre NICs no host.
