---
sidebar: sidebar 
permalink: vmware/vmware-vsphere-datastores-fg.html 
keywords: vSphere, datastore, NFS, nconnect, FlexGroup, session trunking 
summary: Esta página descreve as práticas recomendadas para a implementação do ONTAP FlexGroup volumes em um ambiente VMware vSphere. 
---
= Volumes FlexGroup
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ../media/


[role="lead"]
Use o ONTAP e o FlexGroup volumes com o VMware vSphere para armazenamentos de dados simples e dimensionáveis que aproveitam todo o poder de um cluster ONTAP inteiro.

O ONTAP 9,8, juntamente com as ferramentas do ONTAP para VMware vSphere 9,8-9,13 e o plug-in SnapCenter para VMware 4,4 e versões mais recentes, adicionou suporte para datastores com suporte de volume FlexGroup no vSphere. O FlexGroup volumes simplifica a criação de grandes armazenamentos de dados e cria automaticamente os volumes constituintes distribuídos necessários no cluster do ONTAP para obter o máximo de desempenho a partir de um sistema ONTAP.

Use o FlexGroup volumes com vSphere se você precisar de um único armazenamento de dados dimensionável vSphere com o poder de um cluster ONTAP completo ou se você tiver workloads de clonagem muito grandes que podem se beneficiar do mecanismo de clonagem do FlexGroup mantendo o cache clone aquecido constantemente.



== Descarga de cópia

Além de testes extensivos do sistema com cargas de trabalho do vSphere, o ONTAP 9.8 adicionou um novo mecanismo de descarga de cópia para datastores FlexGroup. Este novo sistema usa um mecanismo de cópia melhorado para replicar arquivos entre constituintes em segundo plano, permitindo o acesso à origem e ao destino. Esse cache constituinte-local é então usado para instanciar rapidamente clones da VM sob demanda.

Para ativar a descarga de cópia otimizada do FlexGroup, consulte https://kb.netapp.com/onprem/ontap/dm/VAAI/How_to_Configure_ONTAP_FlexGroups_to_allow_VAAI_copy_offload["Como configurar volumes ONTAP FlexGroup para permitir descarga de cópia VAAI"]

É possível que, se você usar a clonagem do VAAI, mas não clonar o suficiente para manter o cache aquecido, seus clones podem não ser mais rápidos do que uma cópia baseada em host. Se for esse o caso, você pode ajustar o tempo limite do cache para melhor atender às suas necessidades.

Considere o seguinte cenário:

* Você criou um novo FlexGroup com 8 constituintes
* O tempo limite do cache para o novo FlexGroup é definido para 160 minutos


Nesse cenário, os primeiros 8 clones a serem concluídos serão cópias completas, não clones de arquivos locais. Qualquer clonagem adicional dessa VM antes que o tempo limite de 160 segundos expire usará o mecanismo de clone de arquivo dentro de cada constituinte de uma forma round-robin para criar cópias quase imediatas distribuídas uniformemente pelos volumes constituintes.

Cada novo trabalho clone que um volume recebe repõe o tempo limite. Se um volume constituinte no exemplo FlexGroup não receber uma solicitação de clone antes do tempo limite, o cache para essa VM específica será limpo e o volume precisará ser preenchido novamente. Além disso, se a origem do clone original mudar (por exemplo, você atualizou o modelo), então o cache local em cada componente será invalidado para evitar qualquer conflito. Como dito anteriormente, o cache é ajustável e pode ser configurado para corresponder às necessidades do seu ambiente.

Para obter mais informações sobre como usar o FlexGroup volumes com VAAI, consulte este artigo da KB: https://kb.netapp.com/?title=onprem%2Fontap%2Fdm%2FVAAI%2FVAAI%3A_How_does_caching_work_with_FlexGroups%253F["VAAI: Como o armazenamento em cache funciona com o FlexGroup volumes?"^]

Em ambientes onde você não consegue aproveitar ao máximo o cache FlexGroup, mas ainda exige clonagem rápida entre volumes, considere o uso de vVols. A clonagem entre volumes com vVols é muito mais rápida do que usar datastores tradicionais e não depende de um cache.



== Definições de QoS

A configuração do QoS no nível FlexGroup usando o Gerenciador de sistema do ONTAP ou o shell do cluster é suportada, no entanto, não fornece reconhecimento de VM ou integração do vCenter.

O QoS (IOPS máx/min) pode ser definido em VMs individuais ou em todas as VMs em um datastore na IU do vCenter ou por meio de APIs REST usando ferramentas do ONTAP. A configuração de QoS em todas as VMs substitui todas as configurações separadas por VM. As configurações não se estendem a VMs novas ou migradas no futuro; defina a QoS nas novas VMs ou reaplique QoS a todas as VMs no datastore.

Observe que o VMware vSphere trata todas as IO para um datastore NFS como uma única fila por host, e a regulagem da QoS em uma VM pode afetar a performance de outras VMs no mesmo datastore para esse host. Isso está em contraste com o vVols, que pode manter suas configurações de política de QoS se eles migrarem para outro datastore e não afetarem o IO de outras VMs quando forem controlados.



== Métricas

O ONTAP 9.8 também adicionou novas métricas de performance baseadas em arquivos (IOPS, taxa de transferência e latência) para o FlexGroup Files, e essas métricas podem ser visualizadas nas ferramentas do ONTAP para os relatórios de VM e painel do VMware vSphere. O plug-in das ferramentas do ONTAP para VMware vSphere também permite que você defina regras de qualidade do serviço (QoS) usando uma combinação de IOPS máximo e/ou mínimo. Eles podem ser configurados em todas as VMs em um datastore ou individualmente para VMs específicas.



== Práticas recomendadas

* Use as ferramentas do ONTAP para criar datastores do FlexGroup para garantir que o FlexGroup seja criado de forma otimizada e que as políticas de exportação sejam configuradas para corresponder ao seu ambiente vSphere. No entanto, depois de criar o volume FlexGroup com as ferramentas do ONTAP, você descobrirá que todos os nós do cluster do vSphere estão usando um único endereço IP para montar o datastore. Isso pode resultar em um gargalo na porta de rede. Para evitar esse problema, desmonte o datastore e remonte-o usando o assistente padrão do vSphere datastore usando um nome DNS de round-robin que carrega o balanceamento entre LIFs no SVM. Depois de remontar, as ferramentas do ONTAP poderão gerenciar o datastore novamente. Se as ferramentas do ONTAP não estiverem disponíveis, use os padrões do FlexGroup e crie sua política de exportação seguindo as diretrizes do link:vmware-vsphere-datastores-nfs.html["Datastores e protocolos - NFS"].
* Ao dimensionar um armazenamento de dados do FlexGroup, lembre-se de que o FlexGroup consiste em vários volumes FlexVol menores que criam um namespace maior. Como tal, dimensione o datastore para ter pelo menos 8x (assumindo os componentes 8 padrão) o tamanho do seu maior arquivo VMDK mais 10-20% de espaço livre não utilizado para permitir flexibilidade no rebalanceamento. Por exemplo, se você tiver um VMDK de 6TB TB no seu ambiente, dimensione o datastore do FlexGroup não menor que 52,8TB TB (6x8 a 10%).
* VMware e NetApp suportam entroncamento de sessão NFSv4,1 começando com ONTAP 9.14,1. Consulte as notas da ferramenta de Matriz de interoperabilidade (IMT) do NetApp NFS 4,1 para obter detalhes específicos da versão. O NFSv3 não oferece suporte a vários caminhos físicos para um volume, mas oferece suporte ao nconnect a partir do vSphere 8.0U2. Mais informações sobre o nconnect podem ser encontradas no link:https://docs.netapp.com/us-en/netapp-solutions/vmware/vmware-vsphere8-nfs-nconnect.html["NFSv3 nLigue o recurso ao NetApp e VMware"].
* Use o plug-in NFS para VMware VAAI para descarga de cópia. Observe que, embora a clonagem seja aprimorada em um datastore FlexGroup, como mencionado anteriormente, o ONTAP não oferece vantagens significativas de desempenho em comparação com a cópia do host ESXi ao copiar VMs entre volumes FlexVol e/ou FlexGroup. Portanto, considere seus workloads de clonagem ao decidir usar volumes VAAI ou FlexGroup. Modificar o número de volumes constituintes é uma forma de otimizar a clonagem baseada em FlexGroup. Como está ajustando o tempo limite do cache mencionado anteriormente.
* Use as ferramentas do ONTAP para o VMware vSphere 9,8-9,13 para monitorar a performance das VMs FlexGroup usando métricas do ONTAP (painel e relatórios de VM) e gerenciar a QoS em VMs individuais. Essas métricas não estão disponíveis atualmente por meio de comandos ou APIs do ONTAP.
* O plug-in do SnapCenter para VMware vSphere versão 4,4 e posterior oferece suporte ao backup e à recuperação de VMs em um datastore FlexGroup no sistema de storage primário. A VCS 4,6 adiciona suporte ao SnapMirror para datastores baseados em FlexGroup. Usar snapshots e replicação baseados em array é a maneira mais eficiente de proteger seus dados.

