---
sidebar: sidebar 
permalink: vmware/vmware-vsphere-why.html 
keywords: introduction, unified storage, virtual volumes, storage efficiency, hybrid cloud 
summary: Os clientes escolhem com confiança o ONTAP para vSphere devido às suas soluções de storage SAN e nas unificadas e à nova arquitetura de storage desagregado simplificada, que é incluída nos arrays SAN mais recentes. Essa plataforma oferece proteção excecional contra snapshot e ferramentas de gerenciamento robustas. Ao descarregar funções para um storage dedicado, o ONTAP maximiza os recursos do host, reduz custos e mantém o desempenho ideal. Além disso, as cargas de trabalho podem ser facilmente migradas usando o Storage vMotion em VMFS, NFS ou vVols. 
---
= Por que o ONTAP para VMware vSphere?
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ../media/


[role="lead"]
Os clientes escolhem com confiança o ONTAP para vSphere para soluções de storage SAN e nas. A nova arquitetura de storage desagregado simplificada, incluída nos arrays all SAN mais recentes, oferece uma experiência simplificada familiar aos administradores de storage SAN, mantendo a maioria das integrações e conjunto de recursos dos sistemas ONTAP tradicionais. Os sistemas ONTAP oferecem proteção excecional contra snapshot e ferramentas de gerenciamento robustas. Ao descarregar funções para um storage dedicado, o ONTAP maximiza os recursos do host, reduz custos e mantém o desempenho ideal. Além disso, as cargas de trabalho podem ser facilmente migradas usando o Storage vMotion em VMFS, NFS ou vVols.



== As vantagens de usar o ONTAP para vSphere

Há muitos motivos pelos quais dezenas de milhares de clientes escolheram o ONTAP como sua solução de storage para o vSphere, como um sistema de storage unificado compatível com protocolos SAN e nas, recursos robustos de proteção de dados usando snapshots com uso eficiente de espaço e diversas ferramentas para ajudar você a gerenciar dados de aplicações. O uso de um sistema de storage separado do hipervisor permite descarregar várias funções e maximizar seu investimento nos sistemas de host vSphere. Essa abordagem não só garante que os recursos de host estejam focados nas cargas de trabalho dos aplicativos, mas também evita efeitos aleatórios de desempenho nos aplicativos das operações de storage.

O uso do ONTAP em conjunto com o vSphere é uma ótima combinação que permite reduzir as despesas de hardware do host e software VMware. Você também pode proteger seus dados a um custo menor com alta performance consistente. Como as cargas de trabalho virtualizadas são móveis, você pode explorar diferentes abordagens usando o Storage vMotion para mover VMs entre armazenamentos de dados VMFS, NFS ou vVols, tudo no mesmo sistema de storage.

Aqui estão os principais fatores que os clientes valorizam hoje:

* *Armazenamento unificado.* Os sistemas que executam o ONTAP são unificados de várias maneiras significativas. Originalmente, essa abordagem se referia aos protocolos nas e SAN, e a ONTAP continua a ser uma plataforma líder para SAN, juntamente com sua força original no nas. No mundo vSphere, essa abordagem também pode significar um sistema unificado para infraestrutura de desktop virtual (VDI), juntamente com a infraestrutura de servidor virtual (VSI). Os sistemas que executam o ONTAP geralmente são mais baratos para VSI do que os arrays empresariais tradicionais e ainda têm recursos avançados de eficiência de storage para lidar com a VDI no mesmo sistema. O ONTAP também unifica uma variedade de Mídia de armazenamento, de SSDs a SATA, e pode estender isso facilmente para a nuvem. Não há necessidade de comprar um sistema operacional de armazenamento para desempenho, outro para arquivos e mais um para a nuvem. ONTAP une todos eles.
* *All SAN Array (ASA).* Os sistemas ONTAP ASA mais recentes (começando com A1K, A90, A70, A50, A30 e A20) foram criados com base em uma nova arquitetura de storage que elimina o paradigma tradicional de storage da ONTAP de gerenciamento de agregados e volumes. Como não há compartilhamentos de sistema de arquivos, não há necessidade de volumes! Todo o storage anexado a um par de HA é Tratado como uma zona de disponibilidade de storage (SAZ) comum na qual LUNs e namespaces NVMe são provisionados como "unidades de storage" (SUS). Os sistemas ASA mais recentes foram projetados para serem simples de gerenciar, com uma experiência familiar para administradores de storage de SAN. Essa nova arquitetura é ideal para ambientes vSphere, pois permite o gerenciamento fácil de recursos de storage e oferece uma experiência simplificada para administradores de storage SAN. A arquitetura do ASA também é compatível com a mais recente tecnologia NVMe over Fabrics (NVMe-of), que oferece ainda mais performance e escalabilidade para workloads vSphere.
* *Tecnologia Snapshot.* A ONTAP foi a primeira a fornecer tecnologia snapshot para proteção de dados, e continua sendo a mais avançada do setor. Essa abordagem com uso eficiente de espaço para proteção de dados foi estendida para oferecer suporte às APIs do VMware vSphere para Array Integration (VAAI). Essa integração permite que você aproveite os recursos de snapshot do ONTAP para operações de backup e restauração, reduzindo o impacto no seu ambiente de produção. Essa abordagem também permite que você use snapshots para recuperação rápida de VMs, reduzindo o tempo e o esforço necessários para restaurar os dados. Além disso, a tecnologia de snapshot da ONTAP é integrada às soluções de recuperação de site em tempo real (VLSR, anteriormente Gerenciador de recuperação de site [SRM]) da VMware, fornecendo uma estratégia abrangente de proteção de dados para o seu ambiente virtualizado.
* *Gerenciamento baseado em políticas de armazenamento e volumes virtuais.* O NetApp foi um dos primeiros parceiros de design da VMware no desenvolvimento do vSphere Virtual volumes (vVols), fornecendo informações arquitetônicas e suporte antecipado para vVols e VMware vSphere APIs for Storage Awareness (VASA). Essa abordagem não só trouxe gerenciamento granular de storage de VM para o VMFS, mas também suportou a automação do provisionamento de storage por meio do gerenciamento baseado em políticas de storage. Com essa abordagem, os arquitetos de storage podem projetar pools de storage com recursos diferentes que podem ser facilmente consumidos pelos administradores de VM. A ONTAP lidera o setor de storage na escala da evolução, dando suporte a centenas de milhares de vols em um único cluster, enquanto os fornecedores de array empresarial e flash arrays menores oferecem suporte a apenas milhares de vols por array. O NetApp também está impulsionando a evolução do gerenciamento granular de VM com os próximos recursos.
* *Eficiência de armazenamento.* Embora a NetApp tenha sido a primeira a fornecer deduplicação para cargas de trabalho de produção, essa inovação não foi a primeira ou última nessa área. Ele começou com snapshots, um mecanismo de proteção de dados com uso eficiente de espaço sem efeito de performance e a tecnologia FlexClone para fazer cópias de leitura/gravação instantaneamente das VMs para uso em produção e backup. A NetApp passou a fornecer recursos inline, incluindo deduplicação, compactação e deduplicação de bloco zero, para aproveitar a maior parte do storage com SSDs caros. O ONTAP também adicionou a capacidade de embalar operações e arquivos de e/S menores em um bloco de disco usando a compactação. A combinação desses recursos resultou em que os clientes geralmente veem economias de até 5:1 dólares para VSI e até 30:1 dólares para VDI. A mais nova geração de sistemas ONTAP também inclui compactação e deduplicação aceleradas por hardware, o que pode melhorar ainda mais a eficiência de storage e reduzir custos. Essa abordagem permite armazenar mais dados em menos espaço, reduzindo o custo geral de storage e melhorando a performance. A NetApp está tão confiante em seus recursos de eficiência de storage que oferece um link:https://www.netapp.com/pdf.html?item=/media/79014-ng-937-Efficiency-Guarantee-Customer-Flyer.pdf [Garantia de eficiência].
* *Multilocação.* A ONTAP é líder em alocação a vários clientes, permitindo que você crie várias máquinas virtuais de storage (SVMs) em um único cluster. Essa abordagem permite isolar workloads e fornecer níveis de serviço diferentes para locatários diferentes, o que a torna ideal para fornecedores de serviços e empresas de grande porte. A última geração de sistemas ONTAP também inclui suporte para gerenciamento de capacidade tenente. Esse recurso permite definir limites de capacidade para cada locatário, garantindo que nenhum locatário possa consumir todos os recursos disponíveis. Essa abordagem ajuda a garantir que todos os locatários recebam o nível de serviço que esperam, além de fornecer um alto nível de segurança e isolamento entre os locatários. Além disso, os recursos de alocação a vários clientes da ONTAP são integrados à plataforma vSphere da VMware, permitindo que você gerencie e monitore facilmente seu ambiente virtualizado por meio https://docs.netapp.com/us-en/ontap-tools-vmware-vsphere-10/index.html["Ferramentas do ONTAP para VMware vSphere"] de e https://docs.netapp.com/us-en/data-infrastructure-insights/["Insights da infraestrutura de dados"].
* *Nuvem híbrida.* Sejam usadas para nuvem privada no local, infraestrutura de nuvem pública ou uma nuvem híbrida que combina o melhor dos dois, as soluções da ONTAP ajudam você a criar seu Data Fabric para otimizar e otimizar o gerenciamento de dados. Comece com sistemas all-flash de alta performance e combine-os com sistemas de storage em disco ou em nuvem para proteção de dados e computação em nuvem. Aproveite o suporte avançado para as tecnologias OpenStack e de contêiner, conforme necessário. O NetApp também oferece backup baseado em nuvem (nuvem SnapMirror, Cloud Backup Service e Cloud Sync) e ferramentas de arquivamento e disposição em camadas de storage (FabricPool) para ONTAP para ajudar a reduzir as despesas operacionais e aproveitar o amplo alcance da nuvem.
* *E muito mais.* Aproveite a performance extrema dos arrays NetApp AFF A-Series para acelerar sua infraestrutura virtualizada e gerenciar custos. Aproveite operações totalmente ininterruptas, desde a manutenção até os upgrades até a substituição completa do seu sistema de storage, usando clusters ONTAP com escalabilidade horizontal. Proteger dados em repouso com os recursos de criptografia do NetApp sem custo adicional. Certifique-se de que o desempenho atenda aos níveis de serviço de negócios por meio de recursos de qualidade de serviço refinados. Todos eles fazem parte da ampla variedade de recursos fornecidos com o ONTAP, o software de gerenciamento de dados empresariais líder do setor.

