---
sidebar: sidebar 
permalink: vmware/vmware-vsphere-why.html 
keywords: introduction, unified storage, virtual volumes, storage efficiency, hybrid cloud 
summary: Os clientes escolhem com confiança o ONTAP para vSphere devido às suas soluções de storage SAN e nas unificadas e à nova arquitetura de storage desagregado simplificada, que é incluída nos arrays SAN mais recentes. Essa plataforma oferece proteção excecional contra snapshot e ferramentas de gerenciamento robustas. Ao descarregar funções para um storage dedicado, o ONTAP maximiza os recursos do host, reduz custos e mantém o desempenho ideal. Além disso, as cargas de trabalho podem ser facilmente migradas usando o Storage vMotion em VMFS, NFS ou vVols. 
---
= Por que o ONTAP para VMware vSphere?
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ../media/


[role="lead"]
Os clientes selecionam com confiança o ONTAP para vSphere para soluções de armazenamento SAN e NAS.  A nova arquitetura simplificada de armazenamento desagregado, presente nos mais recentes All SAN Arrays, proporciona uma experiência simplificada e familiar aos administradores de armazenamento SAN, mantendo a maioria das integrações e o conjunto de recursos dos sistemas ONTAP tradicionais.  Os sistemas ONTAP fornecem proteção excepcional de instantâneos e ferramentas de gerenciamento robustas.  Ao transferir funções para armazenamento dedicado, o ONTAP maximiza os recursos do host, reduz custos e mantém o desempenho ideal.  Além disso, as cargas de trabalho podem ser facilmente migradas usando o Storage vMotion entre VMFS, NFS ou vVols.



== As vantagens de usar o ONTAP para vSphere

Há muitos motivos pelos quais dezenas de milhares de clientes escolheram o ONTAP como sua solução de storage para o vSphere, como um sistema de storage unificado compatível com protocolos SAN e nas, recursos robustos de proteção de dados usando snapshots com uso eficiente de espaço e diversas ferramentas para ajudar você a gerenciar dados de aplicações. O uso de um sistema de storage separado do hipervisor permite descarregar várias funções e maximizar seu investimento nos sistemas de host vSphere. Essa abordagem não só garante que os recursos de host estejam focados nas cargas de trabalho dos aplicativos, mas também evita efeitos aleatórios de desempenho nos aplicativos das operações de storage.

Usar o ONTAP junto com o vSphere é uma ótima combinação que permite reduzir despesas com hardware de host e software VMware.  Você também pode proteger seus dados a um custo menor com alto desempenho consistente.  Como as cargas de trabalho virtualizadas são móveis, você pode explorar diferentes abordagens usando o Storage vMotion para mover VMs entre datastores VMFS, NFS ou vVols , tudo no mesmo sistema de armazenamento.

Aqui estão os principais fatores que os clientes valorizam hoje:

* *Armazenamento unificado.*  Os sistemas que executam o ONTAP são unificados de várias maneiras significativas.  Originalmente, essa abordagem se referia aos protocolos NAS e SAN, e o ONTAP continua sendo uma plataforma líder para SAN, juntamente com sua força original no NAS.  No mundo do vSphere, essa abordagem também pode significar um sistema unificado para infraestrutura de desktop virtual (VDI) junto com infraestrutura de servidor virtual (VSI).  Os sistemas que executam ONTAP geralmente são mais baratos para VSI do que os arrays empresariais tradicionais e ainda têm recursos avançados de eficiência de armazenamento para lidar com VDI no mesmo sistema.  O ONTAP também unifica uma variedade de mídias de armazenamento, de SSDs a SATA, e pode estendê-las facilmente para a nuvem.  Não há necessidade de comprar um sistema operacional de armazenamento para desempenho, outro para arquivos e ainda outro para a nuvem.  ONTAP une todos eles.
* *All SAN Array (ASA).* Os sistemas ONTAP ASA mais recentes (começando com A1K, A90, A70, A50, A30 e A20) foram criados com base em uma nova arquitetura de storage que elimina o paradigma tradicional de storage da ONTAP de gerenciamento de agregados e volumes. Como não há compartilhamentos de sistema de arquivos, não há necessidade de volumes! Todo o storage anexado a um par de HA é Tratado como uma zona de disponibilidade de storage (SAZ) comum na qual LUNs e namespaces NVMe são provisionados como "unidades de storage" (SUS). Os sistemas ASA mais recentes foram projetados para serem simples de gerenciar, com uma experiência familiar para administradores de storage de SAN. Essa nova arquitetura é ideal para ambientes vSphere, pois permite o gerenciamento fácil de recursos de storage e oferece uma experiência simplificada para administradores de storage SAN. A arquitetura do ASA também é compatível com a mais recente tecnologia NVMe over Fabrics (NVMe-of), que oferece ainda mais performance e escalabilidade para workloads vSphere.
* *Tecnologia Snapshot.* A ONTAP foi a primeira a fornecer tecnologia snapshot para proteção de dados, e continua sendo a mais avançada do setor. Essa abordagem com uso eficiente de espaço para proteção de dados foi estendida para oferecer suporte às APIs do VMware vSphere para Array Integration (VAAI). Essa integração permite que você aproveite os recursos de snapshot do ONTAP para operações de backup e restauração, reduzindo o impacto no seu ambiente de produção. Essa abordagem também permite que você use snapshots para recuperação rápida de VMs, reduzindo o tempo e o esforço necessários para restaurar os dados. Além disso, a tecnologia de snapshot da ONTAP é integrada às soluções de recuperação de site em tempo real (VLSR, anteriormente Gerenciador de recuperação de site [SRM]) da VMware, fornecendo uma estratégia abrangente de proteção de dados para o seu ambiente virtualizado.
* *Gerenciamento baseado em políticas de armazenamento e volumes virtuais.*  A NetApp foi uma das primeiras parceiras de design da VMware no desenvolvimento do vSphere Virtual Volumes (vVols), fornecendo informações arquitetônicas e suporte inicial para vVols e VMware vSphere APIs for Storage Awareness (VASA).  Essa abordagem não apenas trouxe gerenciamento granular de armazenamento de VM para o VMFS, como também ofereceu suporte à automação do provisionamento de armazenamento por meio do gerenciamento baseado em políticas de armazenamento.  Essa abordagem permite que arquitetos de armazenamento projetem pools de armazenamento com diferentes recursos que podem ser facilmente consumidos por administradores de VM.  ONTAP lidera o setor de armazenamento em escala de vVol, dando suporte a centenas de milhares de vVols em um único cluster, enquanto fornecedores de matrizes corporativas e matrizes flash menores dão suporte a apenas alguns milhares de vVols por matriz.  A NetApp também está impulsionando a evolução do gerenciamento granular de VMs com recursos futuros.
* *Eficiência de armazenamento.*  Embora a NetApp tenha sido a primeira a oferecer desduplicação para cargas de trabalho de produção, essa inovação não foi a primeira nem a última nessa área.  Tudo começou com snapshots, um mecanismo de proteção de dados com eficiência de espaço e sem impacto no desempenho, juntamente com a tecnologia FlexClone para fazer instantaneamente cópias de leitura/gravação de VMs para uso em produção e backup.  A NetApp passou a fornecer recursos em linha, incluindo desduplicação, compactação e desduplicação de bloco zero, para extrair o máximo de armazenamento de SSDs caros.  O ONTAP também adicionou a capacidade de compactar operações de E/S e arquivos menores em um bloco de disco usando compactação.  A combinação desses recursos fez com que os clientes geralmente observassem economias de até 5:1 para VSI e até 30:1 para VDI.  A mais nova geração de sistemas ONTAP também inclui compactação e desduplicação aceleradas por hardware, o que pode melhorar ainda mais a eficiência do armazenamento e reduzir custos.  Essa abordagem permite que você armazene mais dados em menos espaço, reduzindo o custo geral de armazenamento e melhorando o desempenho.  A NetApp está tão confiante em seus recursos de eficiência de armazenamento que oferece um link: https://www.netapp.com/pdf.html?item=/media/79014-ng-937-Efficiency-Guarantee-Customer-Flyer.pdf [Garantia de Eficiência^].
* *Multilocação.*  O ONTAP é líder em multilocação há muito tempo, permitindo que você crie várias máquinas virtuais de armazenamento (SVMs) em um único cluster.  Essa abordagem permite isolar cargas de trabalho e fornecer diferentes níveis de serviço para diferentes locatários, tornando-a ideal para provedores de serviços e grandes empresas.  A última geração de sistemas ONTAP também inclui suporte para gerenciamento de capacidade de locatários.  Esse recurso permite que você defina limites de capacidade para cada locatário, garantindo que nenhum locatário possa consumir todos os recursos disponíveis.  Essa abordagem ajuda a garantir que todos os inquilinos recebam o nível de serviço esperado, ao mesmo tempo em que proporciona um alto nível de segurança e isolamento entre eles.  Além disso, os recursos de multilocação do ONTAP são integrados à plataforma vSphere da VMware, permitindo que você gerencie e monitore facilmente seu ambiente virtualizado por meio de https://docs.netapp.com/us-en/ontap-tools-vmware-vsphere-10/index.html["Ferramentas do ONTAP para VMware vSphere"] e https://docs.netapp.com/us-en/data-infrastructure-insights/["Insights da infraestrutura de dados"] .
* *Nuvem híbrida.*  Seja usado para nuvem privada local, infraestrutura de nuvem pública ou uma nuvem híbrida que combina o melhor de ambas, as soluções ONTAP ajudam você a construir sua estrutura de dados para simplificar e otimizar o gerenciamento de dados.  Comece com sistemas all-flash de alto desempenho e, em seguida, combine-os com sistemas de armazenamento em disco ou em nuvem para proteção de dados e computação em nuvem.  Escolha entre Azure, AWS, IBM ou Google Cloud para otimizar custos e evitar aprisionamento. Aproveite o suporte avançado para OpenStack e tecnologias de contêiner conforme necessário.  A NetApp também oferece backup baseado em nuvem (SnapMirror Cloud, Cloud Backup Service e Cloud Sync) e ferramentas de arquivamento e níveis de armazenamento (FabricPool) para ONTAP para ajudar a reduzir despesas operacionais e aproveitar o amplo alcance da nuvem.
* *E muito mais.* Aproveite a performance extrema dos arrays NetApp AFF A-Series para acelerar sua infraestrutura virtualizada e gerenciar custos. Aproveite operações totalmente ininterruptas, desde a manutenção até os upgrades até a substituição completa do seu sistema de storage, usando clusters ONTAP com escalabilidade horizontal. Proteger dados em repouso com os recursos de criptografia do NetApp sem custo adicional. Certifique-se de que o desempenho atenda aos níveis de serviço de negócios por meio de recursos de qualidade de serviço refinados. Todos eles fazem parte da ampla variedade de recursos fornecidos com o ONTAP, o software de gerenciamento de dados empresariais líder do setor.

