---
sidebar: sidebar 
permalink: vmware/vmware-srm-ontap-tools-features.html 
keywords: vmware, site, recovery manager, vsrm, vsphere, ipv6, support, rest, api, replication, ccols, spbm, srm, appliance based 
summary: Suporte a recursos, limites e vVols com ferramentas ONTAP. 
---
= Novos recursos com VLSR/SRM e Ferramentas ONTAP
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ../media/


[role="lead"]
Com a transição do dispositivo virtual legado, as ferramentas do ONTAP trazem uma grande variedade de novos recursos, limites mais altos e novo suporte a vVols.



== Versões mais recentes do vSphere e do Site Recovery Manager

A NetApp compartilhou uma parceria profunda com a VMware por quase duas décadas e se esforça para fornecer suporte para os lançamentos mais recentes o mais rápido possível. Verifique sempre o NetApp https://mysupport.netapp.com/matrix/imt.jsp?components=84943;&solution=1777&isHWU&src=IMT["Ferramenta de Matriz de interoperabilidade (IMT)"^] para obter as combinações qualificadas mais recentes de software.



== Suporte para IPv6

IPv6 agora é suportado com as seguintes limitações:

* Não suportado com o SRM 8,2 (8,1, 8,3 e 8. 4 e posteriores são suportados)
* Consulte a https://mysupport.netapp.com/matrix/imt.jsp?components=84943;&solution=1777&isHWU&src=IMT["Ferramenta de Matriz de interoperabilidade (IMT)"^] para obter as versões qualificadas mais recentes.




== Maior escala

As ferramentas ONTAP 10,4 SRA agora podem suportar a escala máxima de VLSR/SRM.

* Número total de VMs protegidas: 5000
* Número de VMs por Grupo de proteção: 1000
* Número total de planos de recuperação: 250
* O número total de grupos de proteção por plano de recuperação é de 250
* Número total de datastores replicados: 255
* Número total de planos de recuperação em execução simultânea. 10




== Replicação síncrona

Um novo recurso muito aguardado é o SnapMirror Synchronous (SM-S) com o ONTAP 9.5 e posterior, que fornece uma solução de replicação de dados granular com RPO zero de volume para suas aplicações de missão crítica. O SM-S requer as ferramentas ONTAP 9,8 ou posterior.



== Compatível com API REST

A configuração do servidor SRA agora pode ser gerenciada por APIS REST. Uma IU Swagger foi adicionada para ajudar a criar seus fluxos de trabalho de automação e pode ser encontrada em seu dispositivo de ferramentas do ONTAP em `https://<appliance>:8443/`.
