---
sidebar: sidebar 
permalink: vmware/vmware-srm-overview.html 
keywords: ontap, vsphere, srm, srm, hybrid, cloud, migration, vmware, site, recovery manager, vsrm,VLSR 
summary: 'A solução ONTAP para o VMware Live Site Recovery (VLSR) e o Gerenciador de recuperação de local (SRM)' 
---
= Recuperação do site ao vivo da VMware com o ONTAP
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ../media/


[role="lead"]
O ONTAP tem sido uma solução de armazenamento líder para o VMware vSphere e, mais recentemente, para o Cloud Foundation, desde que o ESX foi introduzido em datacenters modernos há mais de duas décadas.  A NetApp continua a introduzir sistemas inovadores, como a última geração da série ASA A, juntamente com recursos como a sincronização ativa SnapMirror .  Esses avanços simplificam o gerenciamento, aumentam a resiliência e reduzem o custo total de propriedade (TCO) da sua infraestrutura de TI.

Este documento apresenta a solução ONTAP para VMware Live Site Recovery (VLSR), anteriormente conhecido como Site Recovery Manager (SRM), o software de recuperação de desastres (DR) líder do setor da VMware, incluindo as informações mais recentes sobre o produto e as melhores práticas para otimizar a implantação, reduzir riscos e simplificar o gerenciamento contínuo.


NOTE: Esta documentação substitui o relatório técnico publicado anteriormente _TR-4900: VMware Site Recovery Manager com ONTAP_

As práticas recomendadas complementam outros documentos, como guias e ferramentas de compatibilidade. Eles são desenvolvidos com base em testes de laboratório e extensa experiência de campo por engenheiros e clientes da NetApp. Em alguns casos, as melhores práticas recomendadas podem não ser a opção certa para o seu ambiente; no entanto, geralmente são as soluções mais simples que atendem às necessidades da maioria dos clientes.

Este documento se concentra nos recursos das versões recentes do ONTAP 9 quando usado em conjunto com as ferramentas do ONTAP para VMware vSphere 10,4 (que inclui o adaptador de replicação de armazenamento NetApp [SRA] e o provedor VASA [VP]), bem como o VMware Live Site Recovery 9.



== Por que usar o ONTAP com VLSR ou SRM?

As plataformas de gerenciamento de dados da NetApp com tecnologia ONTAP são algumas das soluções de armazenamento mais amplamente adotadas para VLSR.  Os motivos são muitos: uma plataforma de gerenciamento de dados segura, de alto desempenho e com protocolo unificado (NAS e SAN juntos) que fornece eficiência de armazenamento que define o setor, multilocação, controles de qualidade de serviço, proteção de dados com instantâneos com eficiência de espaço e replicação com SnapMirror.  Tudo isso aproveitando a integração nativa de multi-nuvem híbrida para a proteção de cargas de trabalho do VMware e uma infinidade de ferramentas de automação e orquestração ao seu alcance.

Ao usar o SnapMirror para replicação baseada em array, você aproveita uma das tecnologias mais comprovadas e maduras do ONTAP.  O SnapMirror oferece a vantagem de transferências de dados seguras e altamente eficientes, copiando apenas blocos alterados do sistema de arquivos, não VMs ou armazenamentos de dados inteiros.  Mesmo esses blocos aproveitam a economia de espaço, como desduplicação, compactação e compactação.  Os sistemas ONTAP modernos agora usam o SnapMirror independente de versão, permitindo flexibilidade na seleção de seus clusters de origem e destino.  O SnapMirror realmente se tornou uma das ferramentas mais poderosas disponíveis para recuperação de desastres.

Não importa se você usa armazenamentos de dados tradicionais NFS, iSCSI ou Fibre Channel (agora com suporte para armazenamentos de dados vVols ), o VLSR fornece uma oferta primária robusta que aproveita o melhor dos recursos do ONTAP para recuperação de desastres ou planejamento e orquestração de migração de datacenter.



== Como o VLSR utiliza o ONTAP 9

O VLSR aproveita as tecnologias avançadas de gerenciamento de dados dos sistemas ONTAP integrando-se às ferramentas do ONTAP para VMware vSphere, um dispositivo virtual que inclui três componentes principais:

* O plug-in do ONTAP Tools vCenter, anteriormente conhecido como VSC (Virtual Storage Console), simplifica o gerenciamento de storage e os recursos de eficiência, aprimora a disponibilidade e reduz os custos de storage e a sobrecarga operacional, não importa se você está usando SAN ou nas. Ele usa as práticas recomendadas para provisionar armazenamentos de dados e otimiza as configurações de host ESXi para ambientes de storage de bloco e NFS. Para todos esses benefícios, a NetApp recomenda esse plug-in ao usar o vSphere com sistemas que executam o ONTAP.
* O provedor VASA (ONTAP Tools) oferece suporte à estrutura VMware vStorage APIs for Storage Awareness (VASA). O provedor VASA coneta o vCenter Server com o ONTAP para auxiliar no provisionamento e monitoramento do armazenamento de VM. Isso permitiu o suporte ao VMware Virtual volumes (vVols), o gerenciamento de políticas de storage de VM e o desempenho individual do VM vVols. Ele também fornece alarmes para monitorar a capacidade e conformidade com os perfis.
* O SRA é usado em conjunto com o VLSR para gerenciar a replicação de dados de VM entre locais de produção e recuperação de desastres para armazenamentos de dados VMFS e NFS tradicionais e também para testes sem interrupções de réplicas de DR. Ele ajuda a automatizar as tarefas de descoberta, recuperação e reproteção. Ele inclui um dispositivo de servidor SRA e adaptadores SRA para o servidor Windows SRM e o dispositivo VLSR.


Depois de instalar e configurar os adaptadores SRA no servidor VLSR para proteger armazenamentos de dados não vVols, você pode começar a tarefa de configurar seu ambiente vSphere para recuperação de desastres.

O SRA oferece uma interface de comando e controle para o servidor VLSR gerenciar os volumes ONTAP FlexVol que contêm suas máquinas virtuais (VMs) da VMware, bem como a replicação do SnapMirror que os protege.

A VLSR pode testar seu plano de DR sem interrupções usando a tecnologia FlexClone proprietária da NetApp para fazer clones quase instantâneos de seus armazenamentos de dados protegidos em seu site de DR.  O VLSR cria um sandbox para testes seguros, para que sua organização e seus clientes estejam protegidos em caso de um desastre real, dando a você confiança na capacidade de sua organização de executar um failover durante um desastre.

No caso de um verdadeiro desastre ou mesmo de uma migração planejada, o VLSR permite que você envie quaisquer alterações de última hora para o conjunto de dados por meio de uma atualização final do SnapMirror (se você optar por fazê-lo). Em seguida, ele quebra o espelho e monta o datastore em seus hosts de DR. Nesse ponto, suas VMs podem ser automaticamente ativadas em qualquer ordem de acordo com sua estratégia pré-planejada.


NOTE: Embora os sistemas ONTAP permitam emparelhar SVMs no mesmo cluster para replicação do SnapMirror, esse cenário não é testado e certificado com o VLSR. Portanto, é recomendável usar apenas SVMs de diferentes clusters ao usar o VLSR.



== VLSR com ONTAP e outros casos de uso: Nuvem híbrida e migração

A integração da sua implantação de VLSR com os recursos avançados de gerenciamento de dados do ONTAP permite escala e desempenho significativamente melhores quando comparado com opções de armazenamento local. Mas mais do que isso, ele traz a flexibilidade da nuvem híbrida. A nuvem híbrida permite que você economize dinheiro ao hierarquizar blocos de dados não utilizados do seu array de alto desempenho para o seu hiperescalador preferido usando o FabricPool, que pode ser um armazenamento S3 local, como o NetApp StorageGRID. Você também pode usar o SnapMirror para sistemas baseados em borda com ONTAP Select definido por software ou DR baseado em nuvem usando https://www.equinix.com/partners/netapp["Armazenamento NetApp no ​​Equinix Metal"^], ou outros serviços ONTAP hospedados.

Depois, você pode executar failover de teste no data center de um fornecedor de serviços de nuvem com espaço físico de storage quase zero graças ao FlexClone. Proteger sua organização agora pode custar menos do que nunca.

O VLSR também pode ser usado para executar migrações planejadas utilizando o SnapMirror para transferir eficientemente suas VMs de um data center para outro ou até mesmo dentro do mesmo data center, seja seu, ou por meio de qualquer número de provedores de serviços parceiros da NetApp.
