---
sidebar: sidebar 
permalink: vmware/vmware-srm-deployment_best_practices.html 
keywords: vmware, site, recovery manager, vsrm, svm, layout, segmentation, smt, best, practices, deploy, ontap, tools, vvols, srm, vlsr 
summary: 'Com o ONTAP, o conceito de máquina virtual de storage (SVM) fornece segmentação rigorosa em ambientes multitenant seguros.' 
---
= Práticas recomendadas de implantação
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ../media/


[role="lead"]
As seções a seguir descrevem as práticas recomendadas de implantação com o ONTAP e o VMware SRM.



== Use a versão mais recente das ferramentas do ONTAP 10

O ONTAP Tools 10 fornece melhorias significativas em relação às versões anteriores, incluindo o seguinte:

* failover de teste 8xx mais rápido*
* limpeza e reproteção 2xx mais rápidas*
* failover 32% mais rápido*
* Maior escala
* Suporte nativo para layouts de site compartilhados


*Essas melhorias são baseadas em testes internos e podem variar de acordo com o seu ambiente.



== Layout e segmentação do SVM para SMT

Com o ONTAP, o conceito de máquina virtual de storage (SVM) fornece segmentação rigorosa em ambientes multitenant seguros. Os usuários do SVM em um SVM não podem acessar ou gerenciar recursos de outro. Dessa forma, você pode utilizar a tecnologia ONTAP criando SVMs separadas para diferentes unidades de negócios que gerenciam seus próprios fluxos de trabalho SRM no mesmo cluster para maior eficiência geral de storage.

Considere o gerenciamento do ONTAP usando contas com escopo SVM e LIFs de gerenciamento de SVM para aprimorar não apenas os controles de segurança, mas também a performance. O desempenho é inerentemente maior ao usar conexões com escopo SVM, pois o SRA não é necessário para processar todos os recursos em um cluster inteiro, incluindo recursos físicos. Em vez disso, ele só precisa entender os ativos lógicos que são abstraídos para o SVM específico.



== Práticas recomendadas para gerenciamento de sistemas ONTAP 9

Como mencionado anteriormente, você pode gerenciar clusters do ONTAP usando credenciais de escopo do cluster ou SVM e LIFs de gerenciamento. Para um desempenho ideal, você pode considerar o uso de credenciais com escopo SVM sempre que não estiver usando vVols. No entanto, ao fazer isso, você deve estar ciente de alguns requisitos, e que você perde alguma funcionalidade.

* A conta padrão do vsadmin SVM não tem o nível de acesso necessário para executar tarefas de ferramentas do ONTAP. Portanto, você precisa criar uma nova conta SVM. https://docs.netapp.com/us-en/ontap-tools-vmware-vsphere-10/configure/configure-user-role-and-privileges.html["Configurar as funções de usuário do ONTAP e o Privileges"] Usando o arquivo JSON incluído. Isso pode ser usado para contas com escopo de SVM ou cluster.
* Como o plug-in da IU do vCenter, o provedor VASA e o servidor SRA são todos microsserviços totalmente integrados, você deve adicionar armazenamento ao adaptador SRA no SRM da mesma forma que você adiciona armazenamento na IU do vCenter para ferramentas do ONTAP. Caso contrário, o servidor SRA pode não reconhecer as solicitações enviadas do SRM através do adaptador SRA.
* A verificação de caminho NFS não é realizada ao usar credenciais com escopo SVM, a menos que você primeiro https://docs.netapp.com/us-en/ontap-tools-vmware-vsphere-10/configure/add-storage-backend.html["clusters integrados"] no Gerenciador de ferramentas do ONTAP e associe-as a vCenters. Isso ocorre porque a localização física é logicamente abstraída do SVM. No entanto, isso não é motivo de preocupação, já que os sistemas ONTAP modernos não sofrem mais nenhum declínio de desempenho percetível ao usar caminhos indiretos.
* Economias de espaço agregado devido à eficiência de storage podem não ser relatadas.
* Quando suportado, os espelhos de partilha de carga não podem ser atualizados.
* O log do EMS pode não ser realizado em sistemas ONTAP gerenciados com credenciais de escopo da SVM.

