---
sidebar: sidebar 
permalink: vmware/vmware-vsphere-datastores-top.html 
keywords: vSphere, datastore, VMFS, FC, NVMe/FC, NVMe/TCP, iSCSI, NFS, vVols 
summary: Esta página descreve as práticas recomendadas para a implementação de uma solução de storage ONTAP em um ambiente VMware vSphere. 
---
= Visão geral dos recursos do vSphere datastore e do protocolo
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ../media/


[role="lead"]
Seis protocolos são usados para conetar o VMware vSphere a datastores em um sistema que executa o ONTAP:

* FCP
* NVMe/FC
* NVMe/TCP
* ISCSI
* NFS v3
* NFS v4.1


FCP, NVMe/FC, NVMe/TCP e iSCSI são protocolos de bloco que usam o vSphere Virtual Machine File System (VMFS) para armazenar VMs dentro de LUNs ONTAP ou namespaces NVMe contidos em um ONTAP FlexVol volume. O NFS é um protocolo de arquivos que coloca as VMs em armazenamentos de dados (que são simplesmente volumes ONTAP) sem a necessidade de VMFS. SMB (CIFS), iSCSI, NVMe/TCP ou NFS também podem ser usados diretamente de um sistema operacional convidado para o ONTAP.

As tabelas a seguir apresentam recursos tradicionais de datastore compatíveis com o vSphere com o ONTAP. Essas informações não se aplicam aos armazenamentos de dados vVols, mas geralmente se aplicam ao vSphere 6.x e versões posteriores usando versões compatíveis do ONTAP. Você também pode consultar link:https://www.vmware.com/support/pubs/["Valores máximos de configuração da VMware"^]versões específicas do vSphere para confirmar limites específicos.

|===
| Capacidade/funcionalidade | FC | ISCSI | NVMe-of | NFS 


| Formato | VMFS ou mapeamento de dispositivo bruto (RDM) | VMFS ou RDM | VMFS | N/A. 


| Número máximo de armazenamentos de dados ou LUNs | 1024 LUNs por host | 1024 LUNs por servidor | 256 Namespeces por servidor | O 256 monta o NFS padrão. MaxVolumes é 8. Use as ferramentas do ONTAP para o VMware vSphere para aumentar para 256. 


| Tamanho máximo do datastore | 64 TB | 64 TB | 64 TB | 100TB FlexVol volume ou superior com volume FlexGroup 


| Tamanho máximo do arquivo do datastore | 62 TB | 62 TB | 62 TB | 62TB com ONTAP 9.12.1P2 e posterior 


| Profundidade de fila ideal por LUN ou sistema de ficheiros | 64-256 | 64-256 | Negociação automática | Consulte NFS.MaxQueueDepth em link:vmware-vsphere-settings.html["Host ESXi recomendado e outras configurações do ONTAP"^]. 
|===
A tabela a seguir lista as funcionalidades relacionadas ao armazenamento VMware suportadas.

|===
| Capacidade/recurso | FC | ISCSI | NVMe-of | NFS 


| VMotion | Sim | Sim | Sim | Sim 


| Storage vMotion | Sim | Sim | Sim | Sim 


| VMware HA | Sim | Sim | Sim | Sim 


| Storage Distributed Resource Scheduler (SDRS) | Sim | Sim | Sim | Sim 


| Software de backup habilitado para VMware vStorage APIs for Data Protection (VADP) | Sim | Sim | Sim | Sim 


| Microsoft Cluster Service (MSCS) ou cluster de failover em uma VM | Sim | Sim 1 | Sim 1 | Não suportado 


| Tolerância de falhas | Sim | Sim | Sim | Sim 


| Site Recovery Manager | Sim | Sim | 2 | V3 apenas 2 


| VMs com thin Provisioning (discos virtuais) | Sim | Sim | Sim | Sim esta configuração é o padrão para todas as VMs no NFS quando não estiver usando o VAAI. 


| Multipathing nativo da VMware | Sim | Sim | Sim, usando o novo HPP (High Performance Plugin) | O entroncamento de sessão NFS v4,1 requer ONTAP 9.14,1 e posterior 
|===
A tabela a seguir lista os recursos de gerenciamento de armazenamento ONTAP compatíveis.

|===
| Capacidade/funcionalidade | FC | ISCSI | NVMe-of | NFS 


| Deduplicação de dados | Economia no array | Economia no array | Economia no array | Economia no datastore 


| Thin Provisioning | Datastore ou RDM | Datastore ou RDM | Armazenamento de dados | Armazenamento de dados 


| Redimensione o datastore | Cresça apenas | Cresça apenas | Cresça apenas | Crescer, crescer com crescimento automático e diminuir 


| Plug-ins do SnapCenter para Windows, aplicações Linux (no convidado) | Sim | Sim | Não | Sim 


| Monitoramento e configuração de host usando as ferramentas do ONTAP para VMware vSphere | Sim | Sim | Não | Sim 


| Provisionamento usando as ferramentas do ONTAP para VMware vSphere | Sim | Sim | Não | Sim 
|===
A tabela a seguir lista os recursos de backup suportados.

|===
| Capacidade/funcionalidade | FC | ISCSI | NVMe-of | NFS 


| Snapshots ONTAP | Sim | Sim | Sim | Sim 


| SRM suportado por backups replicados | Sim | Sim | 2 | V3 apenas 2 


| Volume SnapMirror | Sim | Sim | Sim | Sim 


| Acesso à imagem VMDK | Software de backup habilitado para VADP | Software de backup habilitado para VADP | Software de backup habilitado para VADP | Software de backup habilitado para VADP, vSphere Client e vSphere Web Client datastore browser 


| Acesso ao nível do arquivo VMDK | Software de backup habilitado para VADP, somente Windows | Software de backup habilitado para VADP, somente Windows | Software de backup habilitado para VADP, somente Windows | Software de backup habilitado para VADP e aplicativos de terceiros 


| Granularidade NDMP | Armazenamento de dados | Armazenamento de dados | Armazenamento de dados | Datastore ou VM 
|===
*1 *a NetApp recomenda* o uso de iSCSI in-Guest para clusters da Microsoft em vez de VMDKs habilitados para vários gravadores em um armazenamento de dados VMFS. Essa abordagem é totalmente suportada pela Microsoft e VMware, oferece grande flexibilidade com o ONTAP (sistemas SnapMirror para ONTAP no local ou na nuvem), é fácil de configurar e automatizar e pode ser protegido com o SnapCenter. O vSphere 7 adiciona uma nova opção de VMDK em cluster. Isso é diferente dos VMDKs habilitados para vários gravadores, o que requer um armazenamento de dados apresentado por meio do protocolo FC que tem o suporte do VMDK em cluster habilitado. Aplicam-se outras restrições. Consulte a documentação da VMware https://docs.vmware.com/en/VMware-vSphere/7.0/vsphere-esxi-vcenter-server-70-setup-wsfc.pdf["Configuração para Cluster de failover do Windows Server"^] para obter diretrizes de configuração.

2 os armazenamentos de dados usando NVMe-of e NFS v4,1 exigem replicação do vSphere. A replicação baseada em array não é suportada pelo SRM.



== Selecionar um protocolo de armazenamento

Os sistemas que executam o ONTAP dão suporte a todos os principais protocolos de storage. Assim, os clientes podem escolher o que é melhor para o ambiente, dependendo das habilidades da equipe e da infraestrutura de rede existentes e planejadas. Os testes de NetApp geralmente mostraram pouca diferença entre os protocolos executados em velocidades de linha semelhantes, por isso é melhor se concentrar na infraestrutura de rede e nos recursos da equipe sobre o desempenho bruto do protocolo.

Os seguintes fatores podem ser úteis para considerar uma escolha de protocolo:

* * Ambiente atual do cliente.* Embora as equipes DE TI geralmente sejam qualificadas para gerenciar a infraestrutura Ethernet IP, nem todas elas são qualificadas para gerenciar uma malha FC SAN. No entanto, usar uma rede IP de uso geral que não foi projetada para o tráfego de armazenamento pode não funcionar bem. Considere a infraestrutura de rede que você tem em vigor, quaisquer melhorias planejadas e as habilidades e disponibilidade da equipe para gerenciá-los.
* * Facilidade de configuração.* Além da configuração inicial da malha FC (switches e cabeamento adicionais, zoneamento e verificação de interoperabilidade de HBA e firmware), os protocolos de bloco também exigem criação e mapeamento de LUNs e descoberta e formatação pelo SO convidado. Depois que os volumes NFS são criados e exportados, eles são montados pelo host ESXi e prontos para uso. O NFS não tem nenhuma qualificação especial de hardware ou firmware para gerenciar.
* * Facilidade de gestão. * Com os protocolos SAN, se mais espaço for necessário, várias etapas são necessárias, incluindo o crescimento de um LUN, a digitalização novamente para descobrir o novo tamanho e, em seguida, o crescimento do sistema de arquivos). Embora seja possível aumentar um LUN, reduzir o tamanho de um LUN não é, e recuperar espaço não utilizado pode exigir esforço adicional. O NFS permite um dimensionamento fácil para cima ou para baixo, e esse redimensionamento pode ser automatizado pelo sistema de armazenamento. A SAN oferece recuperação de espaço através de comandos DE TRIM/UNMAP do sistema operacional convidado, permitindo que o espaço dos arquivos excluídos seja retornado ao array. Esse tipo de recuperação de espaço é mais difícil com armazenamentos de dados NFS.
* *Transparência do espaço de armazenamento.* A utilização do storage geralmente é mais fácil de ver em ambientes NFS porque o thin Provisioning devolve economia imediatamente. Da mesma forma, a economia de deduplicação e clonagem ficam imediatamente disponíveis para outras VMs no mesmo armazenamento de dados ou para outros volumes do sistema de storage. Normalmente, a densidade da VM também é maior em um armazenamento de dados NFS, o que pode melhorar a economia de deduplicação e reduzir os custos de gerenciamento com menos armazenamentos de dados para gerenciar.




== Layout do datastore

Os sistemas de storage ONTAP oferecem grande flexibilidade na criação de datastores para VMs e discos virtuais. Embora muitas práticas recomendadas do ONTAP sejam aplicadas ao usar o VSC para provisionar armazenamentos de dados para o vSphere (listadas na link:vmware-vsphere-settings.html["Host ESXi recomendado e outras configurações do ONTAP"]seção ), aqui estão algumas diretrizes adicionais a serem consideradas:

* A implantação do vSphere com armazenamentos de dados NFS do ONTAP resulta em uma implementação de alta performance e fácil de gerenciar que fornece taxas de VM para armazenamento de dados que não podem ser obtidas com protocolos de storage baseados em bloco. Essa arquitetura pode resultar em um aumento de dez vezes na densidade do datastore com uma redução correlacionada no número de datastores. Embora um datastore maior possa beneficiar a eficiência de storage e fornecer benefícios operacionais, considere o uso de pelo menos quatro datastores (volumes FlexVol) para armazenar suas VMs em uma única controladora ONTAP para obter o máximo de performance com os recursos de hardware. Essa abordagem também permite que você estabeleça datastores com diferentes políticas de recuperação. Alguns podem ser copiados ou replicados com mais frequência do que outros com base nas necessidades empresariais. Vários armazenamentos de dados não são necessários com o FlexGroup volumes para obter performance, pois são dimensionados de acordo com o design.
* *A NetApp recomenda* o uso de volumes FlexVol para a maioria dos armazenamentos de dados NFS. A partir do ONTAP 9.8, os volumes FlexGroup também são compatíveis para uso como datastores, e geralmente são recomendados para certos casos de uso. Outros contentores de armazenamento do ONTAP, como qtrees, geralmente não são recomendados, porque eles não são atualmente suportados pelas ferramentas do ONTAP para VMware vSphere ou pelo plug-in do NetApp SnapCenter para VMware vSphere. Dito isso, a implantação de datastores como vários qtrees em um único volume pode ser útil para ambientes altamente automatizados que podem se beneficiar de cotas em nível de datastore ou clones de arquivos VM.
* Um bom tamanho para um datastore FlexVol volume é de cerca de 4TB a 8TB. Esse tamanho é um bom ponto de equilíbrio para performance, facilidade de gerenciamento e proteção de dados. Comece pequeno (digamos, 4TB) e cresça o datastore conforme necessário (até o máximo de 100TB). Armazenamentos de dados menores são mais rápidos para se recuperar do backup ou após um desastre e podem ser movidos rapidamente pelo cluster. Considere o uso do dimensionamento automático do ONTAP para aumentar e diminuir automaticamente o volume conforme o espaço usado muda. As ferramentas do ONTAP para o Assistente de provisionamento de datastore do VMware vSphere usam o dimensionamento automático por padrão para novos datastores. A personalização adicional dos limites de crescimento e redução e o tamanho máximo e mínimo podem ser feitos com o System Manager ou com a linha de comando.
* Como alternativa, armazenamentos de dados VMFS podem ser configurados com LUNs acessados pelo FC e iSCSI. O VMFS permite que os LUNs sejam acessados simultaneamente por cada servidor ESX em um cluster. Os armazenamentos de dados VMFS podem ter até 64TB TB de tamanho e consistem em até 32 2TB LUNs (VMFS 3) ou um único LUN 64TB (VMFS 5). O tamanho máximo de LUN do ONTAP é de 128TB GB em sistemas AFF, ASA e FAS. O NetApp geralmente recomenda o uso de um único LUN grande para cada datastore. Assim como o NFS, considere o uso de vários armazenamentos de dados (volumes) para maximizar a performance em uma única controladora ONTAP.
* Os sistemas operacionais Guest (SO) mais antigos precisavam de alinhamento com o sistema de storage para obter o melhor desempenho e eficiência de storage. No entanto, os sistemas operacionais modernos suportados por fornecedores de distribuidores Microsoft e Linux, como a Red Hat, não precisam mais de ajustes para alinhar a partição do sistema de arquivos com os blocos do sistema de armazenamento subjacente em um ambiente virtual. Se você estiver usando um sistema operacional antigo que pode exigir alinhamento, procure na base de conhecimento de suporte da NetApp artigos usando "alinhamento de VM" ou solicite uma cópia do TR-3747 de um Contato de vendas ou parceiro da NetApp.
* Evite o uso de utilitários de desfragmentação no sistema operacional convidado, pois isso não oferece nenhum benefício de desempenho e afeta a eficiência de armazenamento e o uso de espaço instantâneo. Considere também desativar a indexação de pesquisa no SO convidado para desktops virtuais.
* A ONTAP liderou o setor com recursos de eficiência de storage inovadores, permitindo que você aproveite ao máximo seu espaço em disco utilizável. Os sistemas AFF levam essa eficiência ainda mais longe com a deduplicação e a compactação in-line padrão. Os dados são deduplicados em todos os volumes de um agregado. Portanto, você não precisa mais agrupar sistemas operacionais semelhantes e aplicativos semelhantes em um único datastore para maximizar a economia.
* Em alguns casos, talvez você nem precise de um datastore. Para obter o melhor desempenho e capacidade de gerenciamento, evite usar um datastore para aplicativos de e/S de alta qualidade, como bancos de dados e alguns aplicativos. Em vez disso, considere sistemas de arquivos de propriedade de convidados, como sistemas de arquivos NFS ou iSCSI gerenciados pelo convidado ou com RDMs. Para obter orientações específicas sobre aplicações, consulte relatórios técnicos da NetApp para a sua aplicação. Por exemplo, link:../oracle/oracle-overview.html["Bancos de dados Oracle no ONTAP"] tem uma seção sobre virtualização com detalhes úteis.
* Os discos de primeira classe (ou discos virtuais aprimorados) permitem discos gerenciados pelo vCenter, independentemente de uma VM com o vSphere 6,5 e posterior. Embora gerenciados principalmente pela API, eles podem ser úteis com o vVols, especialmente quando gerenciados por ferramentas OpenStack ou Kubernetes. Eles são suportados pelo ONTAP, bem como pelas ferramentas do ONTAP para VMware vSphere.




== Migração de datastore e VM

Ao migrar VMs de um datastore existente em outro sistema de storage para o ONTAP, veja algumas práticas a serem lembradas:

* Use o Storage vMotion para mover o volume de suas máquinas virtuais para o ONTAP. Essa abordagem não só não causa interrupções às VMs em execução, como também permite que recursos de eficiência de storage da ONTAP, como deduplicação e compactação, processem os dados à medida que migram. Considere usar os recursos do vCenter para selecionar várias VMs da lista de inventário e, em seguida, agendar a migração (use a tecla Ctrl enquanto clica em ações) em um momento apropriado.
* Embora você possa Planejar cuidadosamente uma migração para armazenamentos de dados de destino apropriados, muitas vezes é mais simples migrar em massa e depois organizar mais tarde, conforme necessário. Talvez você queira usar essa abordagem para orientar sua migração para diferentes armazenamentos de dados se tiver necessidades específicas de proteção de dados, como diferentes programações do Snapshot.
* A maioria das VMs e seu storage podem ser migrados durante a execução (quente), mas a migração de storage conectado (não no datastore), como ISOs, LUNs ou volumes NFS de outro sistema de storage, pode exigir migração sem interrupção.
* As máquinas virtuais que precisam de uma migração mais cuidadosa incluem bancos de dados e aplicativos que usam armazenamento anexado. Em geral, considere o uso das ferramentas do aplicativo para gerenciar a migração. Para Oracle, considere usar ferramentas Oracle como RMAN ou ASM para migrar os arquivos do banco de dados. Consulte https://docs.netapp.com/us-en/ontap-apps-dbs/oracle/oracle-migration-overview.html["Migração de bancos de dados Oracle para sistemas de storage ONTAP"^] para obter mais informações. Da mesma forma, para o SQL Server, considere usar ferramentas do SQL Server Management Studio ou do NetApp, como o SnapManager para SQL Server ou SnapCenter.




== Ferramentas do ONTAP para VMware vSphere

A prática recomendada mais importante ao usar o vSphere com sistemas executando o ONTAP é instalar e usar as ferramentas do ONTAP para o plug-in do VMware vSphere (anteriormente conhecido como console de armazenamento virtual). Esse plug-in do vCenter simplifica o gerenciamento de storage, aumenta a disponibilidade e reduz os custos de storage e a sobrecarga operacional, seja usando SAN ou nas. Ele usa as práticas recomendadas para provisionar armazenamentos de dados e otimiza as configurações do host ESXi para timeouts multipath e HBA (descritos no Apêndice B). Como é um plug-in do vCenter, ele está disponível para todos os clientes da Web vSphere que se conetam ao servidor vCenter.

O plug-in também ajuda a usar outras ferramentas do ONTAP em ambientes vSphere. Ele permite instalar o plug-in NFS para VMware VAAI, que permite descarga de cópia para o ONTAP para operações de clonagem de VM, reserva de espaço para arquivos de disco virtual espessos e descarga de snapshot ONTAP.

O plug-in também é a interface de gerenciamento para muitas funções do provedor VASA para ONTAP, oferecendo suporte ao gerenciamento baseado em políticas de storage com vVols. Depois que as ferramentas do ONTAP para VMware vSphere forem registradas, use-as para criar perfis de capacidade de storage, mapeá-las para o storage e garantir a conformidade do datastore com os perfis ao longo do tempo. O provedor VASA também fornece uma interface para criar e gerenciar datastores da VVol.

Em geral, *a NetApp recomenda* o uso das ferramentas do ONTAP para a interface do VMware vSphere no vCenter para provisionar armazenamentos de dados tradicionais e vVols para garantir que as práticas recomendadas sejam seguidas.



== Rede geral

A configuração das configurações de rede ao usar o vSphere com sistemas executando o ONTAP é simples e semelhante a outras configurações de rede. Aqui estão algumas coisas a considerar:

* Separe o tráfego de rede de armazenamento de outras redes. Uma rede separada pode ser obtida usando uma VLAN dedicada ou switches separados para armazenamento. Se a rede de armazenamento partilhar caminhos físicos, como uplinks, poderá necessitar de portas de QoS ou uplink adicionais para garantir uma largura de banda suficiente. Não conete os hosts diretamente ao storage; use os switches para ter caminhos redundantes e permitir que o VMware HA funcione sem intervenção. link:vmware-vsphere-network.html["Ligação direta em rede"]Consulte para obter informações adicionais.
* Os frames grandes podem ser usados se desejado e suportados pela sua rede, especialmente ao usar iSCSI. Se forem usados, certifique-se de que estejam configurados de forma idêntica em todos os dispositivos de rede, VLANs e assim por diante no caminho entre o armazenamento e o host ESXi. Caso contrário, você pode ver problemas de desempenho ou conexão. A MTU também deve ser definida de forma idêntica no switch virtual ESXi, na porta VMkernel e também nas portas físicas ou grupos de interface de cada nó ONTAP.
* O NetApp recomenda apenas desativar o controle de fluxo de rede nas portas de rede do cluster dentro de um cluster ONTAP. O NetApp não faz outras recomendações sobre as práticas recomendadas para as portas de rede restantes usadas para tráfego de dados. Você deve ativar ou desativar conforme necessário.  https://www.netapp.com/pdf.html?item=/media/16885-tr-4182pdf.pdf["TR-4182"^]Consulte para obter mais informações sobre o controlo de fluxo.
* Quando os storages ESXi e ONTAP estão conetados a redes de armazenamento Ethernet, *a NetApp recomenda* configurar as portas Ethernet às quais esses sistemas se conetam como portas de borda de protocolo de árvore de expansão rápida (RSTP) ou usando o recurso Cisco PortFast. *A NetApp recomenda* ativar o recurso de tronco de porta de árvore de expansão rápida em ambientes que usam o recurso Cisco PortFast e que têm entroncamento de VLAN 802,1Q habilitado para o servidor ESXi ou os storages ONTAP.
* *A NetApp recomenda* as seguintes práticas recomendadas para agregação de links:
+
** Use switches que suportam agregação de links de portas em dois chassis de switch separados usando uma abordagem de grupo de agregação de links de vários gabinetes, como o Virtual PortChannel (VPC) da Cisco.
** Desative o LACP para portas de switch conetadas ao ESXi a menos que você esteja usando dvSwitches 5,1 ou posterior com o LACP configurado.
** Use o LACP para criar agregados de link para sistemas de storage ONTAP com grupos de interface multimodo dinâmico com hash de porta ou IP.  https://docs.netapp.com/us-en/ontap/networking/combine_physical_ports_to_create_interface_groups.html#dynamic-multimode-interface-group["Gerenciamento de rede"^]Consulte para obter mais orientações.
** Use uma política de agrupamento de hash IP no ESXi ao usar agregação de link estático (por exemplo, EtherChannel) e vSwitches padrão ou agregação de link baseada em LACP com switches distribuídos vSphere. Se a agregação de links não for usada, use "Rota baseada no ID de porta virtual de origem".




A tabela a seguir fornece um resumo dos itens de configuração de rede e indica onde as configurações são aplicadas.

|===
| Item | ESXi | Interrutor | Nó | SVM 


| Endereço IP | VMkernel | 4 | 4 | Sim 


| Agregação de links | Switch virtual | Sim | Sim | 3 


| VLAN | Grupos de portas VMkernel e VM | Sim | Sim | 3 


| Controle de fluxo | NIC | Sim | Sim | 3 


| Spanning tree | Não | Sim | Não | Não 


| MTU (para quadros jumbo) | Switch virtual e porta VMkernel (9000) | Sim (definido para máx.) | Sim (9000) | 3 


| Grupos de failover | Não | Não | Sim (criar) | Sim (selecione) 
|===
3 os LIFs SVM se conetam a portas, grupos de interfaces ou interfaces VLAN que têm VLAN, MTU e outras configurações. No entanto, as configurações não são gerenciadas no nível da SVM.

4 esses dispositivos têm endereços IP próprios para gerenciamento, mas esses endereços não são usados no contexto da rede de armazenamento ESXi.
